import { writeFile } from "node:fs/promises";
import path from "node:path";
import type { Binding, BindValue, Linkable } from "@vyft/core";

// ── Types ────────────────────────────────────────────────────────────

export interface BindingInfo {
  key: string;
  type: "string" | "number";
}

export interface LinkableEntry {
  exportName: string;
  id: string;
  bindings: BindingInfo[];
}

// ── Helpers ──────────────────────────────────────────────────────────

function isBinding(value: unknown): value is Binding {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as Binding).kind === "binding"
  );
}

function isLinkable(value: unknown): value is Linkable {
  if (typeof value !== "object" || value === null) return false;
  const obj = value as Record<string, unknown>;
  const svc = obj["service"];
  return (
    typeof obj["id"] === "string" &&
    typeof svc === "object" &&
    svc !== null &&
    (svc as { kind?: string }).kind === "service"
  );
}

function bindValueType(value: BindValue): "string" | "number" {
  return typeof value === "number" ? "number" : "string";
}

// ── Core Functions ───────────────────────────────────────────────────

/** Derive the env var name using the same convention as `link` in primitives.ts. */
export function linkEnvVarName(id: string, key: string): string {
  return `${id.toUpperCase().replace(/-/g, "_")}_${key.toUpperCase()}`;
}

/** Walk config exports and find objects that satisfy the Linkable interface. */
export function collectLinkables(config: unknown): LinkableEntry[] {
  const entries: LinkableEntry[] = [];
  if (typeof config !== "object" || config === null) return entries;

  for (const [exportName, value] of Object.entries(
    config as Record<string, unknown>,
  )) {
    if (!isLinkable(value)) continue;
    const bindings: BindingInfo[] = [];
    for (const [key, val] of Object.entries(value)) {
      if (isBinding(val)) {
        bindings.push({ key, type: bindValueType(val.value) });
      }
    }
    if (bindings.length > 0) {
      entries.push({ exportName, id: value.id, bindings });
    }
  }

  return entries;
}

/** Generate a JS module that reads bindings from env vars. */
export function generateResourceJs(entries: LinkableEntry[]): string {
  const lines = ["// Auto-generated by vyft generate — do not edit"];

  for (const entry of entries) {
    const props = entry.bindings.map((b) => {
      const envVar = linkEnvVarName(entry.id, b.key);
      const expr =
        b.type === "number"
          ? `Number(process.env.${envVar})`
          : `process.env.${envVar}`;
      return `  ${b.key}: ${expr},`;
    });
    lines.push(`export const ${entry.exportName} = {\n${props.join("\n")}\n};`);
  }

  return `${lines.join("\n")}\n`;
}

/** Generate TypeScript declarations for the resource module. */
export function generateResourceDts(entries: LinkableEntry[]): string {
  const lines = ["// Auto-generated by vyft generate — do not edit"];

  for (const entry of entries) {
    const props = entry.bindings.map((b) => {
      return `  readonly ${b.key}: ${b.type};`;
    });
    lines.push(
      `export declare const ${entry.exportName}: {\n${props.join("\n")}\n};`,
    );
  }

  return `${lines.join("\n")}\n`;
}

/** Load config, collect linkables, and write resource.js + resource.d.ts. */
export async function writeResource(
  config: unknown,
  outputDir: string,
): Promise<LinkableEntry[]> {
  const entries = collectLinkables(config);

  await writeFile(
    path.join(outputDir, "resource.js"),
    generateResourceJs(entries),
  );
  await writeFile(
    path.join(outputDir, "resource.d.ts"),
    generateResourceDts(entries),
  );

  return entries;
}
