import { deepStrictEqual, strictEqual } from "node:assert";
import { describe, it } from "node:test";
import { bindable, service } from "@vyft/platform";
import {
  collectLinkables,
  generateEnvDts,
  linkEnvVarName,
} from "./generate.ts";

// ── Helpers ──────────────────────────────────────────────────────────

function makeLinkable(
  id: string,
  bindings: Record<string, ReturnType<typeof bindable>>,
) {
  const svc = service(id, { image: "test:latest", port: 5432 });
  return { id, service: svc, ...bindings };
}

// ── linkEnvVarName ───────────────────────────────────────────────────

describe("linkEnvVarName()", () => {
  it("uppercases id and key with VYFT_BINDING_ prefix", () => {
    strictEqual(linkEnvVarName("db", "url"), "VYFT_BINDING_DB_URL");
  });

  it("replaces hyphens with underscores", () => {
    strictEqual(linkEnvVarName("my-db", "url"), "VYFT_BINDING_MY_DB_URL");
  });

  it("handles multi-segment ids", () => {
    strictEqual(
      linkEnvVarName("my-app-db", "host"),
      "VYFT_BINDING_MY_APP_DB_HOST",
    );
  });
});

// ── collectLinkables ─────────────────────────────────────────────────

describe("collectLinkables()", () => {
  it("finds linkable objects in config exports", () => {
    const db = makeLinkable("db", {
      url: bindable("postgres://localhost/db"),
      host: bindable("db"),
      port: bindable(5432),
    });
    const config = { db };
    const entries = collectLinkables(config);

    strictEqual(entries.length, 1);
    strictEqual(entries[0]?.exportName, "db");
    strictEqual(entries[0]?.id, "db");
    strictEqual(entries[0]?.bindings.length, 3);
  });

  it("detects binding types correctly", () => {
    const db = makeLinkable("db", {
      url: bindable("postgres://localhost/db"),
      port: bindable(5432),
    });
    const entries = collectLinkables({ db });

    const urlBinding = entries[0]?.bindings.find((b) => b.key === "url");
    const portBinding = entries[0]?.bindings.find((b) => b.key === "port");
    strictEqual(urlBinding?.type, "string");
    strictEqual(portBinding?.type, "number");
  });

  it("skips non-linkable exports", () => {
    const db = makeLinkable("db", { url: bindable("test") });
    const config = {
      db,
      someString: "hello",
      someNumber: 42,
      someService: service("api", { build: "./api" }),
    };
    const entries = collectLinkables(config);

    strictEqual(entries.length, 1);
    strictEqual(entries[0]?.exportName, "db");
  });

  it("handles multiple linkables", () => {
    const db = makeLinkable("db", { url: bindable("pg://db") });
    const cache = makeLinkable("cache", { url: bindable("redis://cache") });
    const entries = collectLinkables({ db, cache });

    strictEqual(entries.length, 2);
    const names = entries.map((e) => e.exportName).sort();
    deepStrictEqual(names, ["cache", "db"]);
  });

  it("returns empty array for null/undefined config", () => {
    strictEqual(collectLinkables(null).length, 0);
    strictEqual(collectLinkables(undefined).length, 0);
  });

  it("skips linkables with no bindings", () => {
    const svc = service("db", { image: "postgres:17", port: 5432 });
    // Has id and service but no bindings
    const db = { id: "db", service: svc };
    const entries = collectLinkables({ db });
    strictEqual(entries.length, 0);
  });
});

// ── generateEnvDts ──────────────────────────────────────────────────

describe("generateEnvDts()", () => {
  it("generates bindings declaration keyed by service ID", () => {
    const entries = [
      {
        exportName: "myDb",
        id: "db",
        bindings: [
          { key: "url", type: "string" as const },
          { key: "port", type: "number" as const },
        ],
      },
    ];

    const dts = generateEnvDts(entries);
    strictEqual(dts.includes("export declare const bindings:"), true);
    strictEqual(dts.includes("readonly db:"), true);
    strictEqual(dts.includes("readonly url: string"), true);
    strictEqual(dts.includes("readonly port: number"), true);
    strictEqual(dts.includes("Auto-generated by vyft generate"), true);
  });

  it("uses service ID not export name as key", () => {
    const entries = [
      {
        exportName: "cache",
        id: "redis",
        bindings: [{ key: "url", type: "string" as const }],
      },
    ];

    const dts = generateEnvDts(entries);
    strictEqual(dts.includes("readonly redis:"), true);
    strictEqual(dts.includes("readonly cache:"), false);
  });

  it("nests multiple linkables under bindings declaration", () => {
    const entries = [
      {
        exportName: "db",
        id: "db",
        bindings: [{ key: "url", type: "string" as const }],
      },
      {
        exportName: "cache",
        id: "redis",
        bindings: [{ key: "url", type: "string" as const }],
      },
    ];

    const dts = generateEnvDts(entries);
    strictEqual(dts.includes("readonly db:"), true);
    strictEqual(dts.includes("readonly redis:"), true);
    strictEqual(dts.includes("export declare const bindings:"), true);
  });

  it("includes env declaration with default keys", () => {
    const dts = generateEnvDts([]);
    strictEqual(dts.includes("export declare const env:"), true);
    strictEqual(dts.includes("readonly NODE_ENV: string"), true);
    strictEqual(dts.includes("readonly PORT: string"), true);
  });

  it("uses provided env keys", () => {
    const dts = generateEnvDts([], ["DATABASE_URL", "PORT"]);
    strictEqual(dts.includes("readonly DATABASE_URL: string"), true);
    strictEqual(dts.includes("readonly PORT: string"), true);
    strictEqual(dts.includes("readonly NODE_ENV: string"), false);
  });
});
