import { deepStrictEqual, strictEqual } from "node:assert";
import { describe, it } from "node:test";
import { bindable, service } from "@vyft/core";
import {
  collectLinkables,
  generateResourceDts,
  generateResourceJs,
  linkEnvVarName,
} from "./generate.ts";

// ── Helpers ──────────────────────────────────────────────────────────

function makeLinkable(
  id: string,
  bindings: Record<string, ReturnType<typeof bindable>>,
) {
  const svc = service(id, { image: "test:latest", port: 5432 });
  return { id, service: svc, ...bindings };
}

// ── linkEnvVarName ───────────────────────────────────────────────────

describe("linkEnvVarName()", () => {
  it("uppercases id and key", () => {
    strictEqual(linkEnvVarName("db", "url"), "DB_URL");
  });

  it("replaces hyphens with underscores", () => {
    strictEqual(linkEnvVarName("my-db", "url"), "MY_DB_URL");
  });

  it("handles multi-segment ids", () => {
    strictEqual(linkEnvVarName("my-app-db", "host"), "MY_APP_DB_HOST");
  });
});

// ── collectLinkables ─────────────────────────────────────────────────

describe("collectLinkables()", () => {
  it("finds linkable objects in config exports", () => {
    const db = makeLinkable("db", {
      url: bindable("postgres://localhost/db"),
      host: bindable("db"),
      port: bindable(5432),
    });
    const config = { db };
    const entries = collectLinkables(config);

    strictEqual(entries.length, 1);
    strictEqual(entries[0]?.exportName, "db");
    strictEqual(entries[0]?.id, "db");
    strictEqual(entries[0]?.bindings.length, 3);
  });

  it("detects binding types correctly", () => {
    const db = makeLinkable("db", {
      url: bindable("postgres://localhost/db"),
      port: bindable(5432),
    });
    const entries = collectLinkables({ db });

    const urlBinding = entries[0]?.bindings.find((b) => b.key === "url");
    const portBinding = entries[0]?.bindings.find((b) => b.key === "port");
    strictEqual(urlBinding?.type, "string");
    strictEqual(portBinding?.type, "number");
  });

  it("skips non-linkable exports", () => {
    const db = makeLinkable("db", { url: bindable("test") });
    const config = {
      db,
      someString: "hello",
      someNumber: 42,
      someService: service("api", { build: "./api" }),
    };
    const entries = collectLinkables(config);

    strictEqual(entries.length, 1);
    strictEqual(entries[0]?.exportName, "db");
  });

  it("handles multiple linkables", () => {
    const db = makeLinkable("db", { url: bindable("pg://db") });
    const cache = makeLinkable("cache", { url: bindable("redis://cache") });
    const entries = collectLinkables({ db, cache });

    strictEqual(entries.length, 2);
    const names = entries.map((e) => e.exportName).sort();
    deepStrictEqual(names, ["cache", "db"]);
  });

  it("returns empty array for null/undefined config", () => {
    strictEqual(collectLinkables(null).length, 0);
    strictEqual(collectLinkables(undefined).length, 0);
  });

  it("skips linkables with no bindings", () => {
    const svc = service("db", { image: "postgres:17", port: 5432 });
    // Has id and service but no bindings
    const db = { id: "db", service: svc };
    const entries = collectLinkables({ db });
    strictEqual(entries.length, 0);
  });
});

// ── generateResourceJs ──────────────────────────────────────────────

describe("generateResourceJs()", () => {
  it("generates JS with env var reads", () => {
    const entries = [
      {
        exportName: "db",
        id: "db",
        bindings: [
          { key: "url", type: "string" as const },
          { key: "host", type: "string" as const },
          { key: "port", type: "number" as const },
        ],
      },
    ];

    const js = generateResourceJs(entries);
    strictEqual(js.includes("process.env.DB_URL"), true);
    strictEqual(js.includes("process.env.DB_HOST"), true);
    strictEqual(js.includes("Number(process.env.DB_PORT)"), true);
    strictEqual(js.includes("export const db"), true);
    strictEqual(js.includes("Auto-generated by vyft generate"), true);
  });

  it("uses correct env var naming for hyphenated ids", () => {
    const entries = [
      {
        exportName: "myDb",
        id: "my-db",
        bindings: [{ key: "url", type: "string" as const }],
      },
    ];

    const js = generateResourceJs(entries);
    strictEqual(js.includes("process.env.MY_DB_URL"), true);
    strictEqual(js.includes("export const myDb"), true);
  });
});

// ── generateResourceDts ─────────────────────────────────────────────

describe("generateResourceDts()", () => {
  it("generates type declarations", () => {
    const entries = [
      {
        exportName: "db",
        id: "db",
        bindings: [
          { key: "url", type: "string" as const },
          { key: "port", type: "number" as const },
        ],
      },
    ];

    const dts = generateResourceDts(entries);
    strictEqual(dts.includes("export declare const db"), true);
    strictEqual(dts.includes("readonly url: string"), true);
    strictEqual(dts.includes("readonly port: number"), true);
    strictEqual(dts.includes("Auto-generated by vyft generate"), true);
  });

  it("handles multiple exports", () => {
    const entries = [
      {
        exportName: "db",
        id: "db",
        bindings: [{ key: "url", type: "string" as const }],
      },
      {
        exportName: "cache",
        id: "cache",
        bindings: [{ key: "url", type: "string" as const }],
      },
    ];

    const dts = generateResourceDts(entries);
    strictEqual(dts.includes("export declare const db"), true);
    strictEqual(dts.includes("export declare const cache"), true);
  });
});
