// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, project_id, environment_id, status, snapshot)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, environment_id, status, error, created, applied, snapshot
`

type CreateDeploymentParams struct {
	ID            pgtype.UUID      `json:"id"`
	ProjectID     pgtype.UUID      `json:"project_id"`
	EnvironmentID pgtype.UUID      `json:"environment_id"`
	Status        DeploymentStatus `json:"status"`
	Snapshot      []byte           `json:"snapshot"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Status,
		arg.Snapshot,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Applied,
		&i.Snapshot,
	)
	return i, err
}

const findDeploymentByRollout = `-- name: FindDeploymentByRollout :one
SELECT deployment_id
  FROM deployment_rollouts
 WHERE resource_id = $1 AND pod_template_hash = $2
 ORDER BY created DESC
 LIMIT 1
`

type FindDeploymentByRolloutParams struct {
	ResourceID      pgtype.UUID `json:"resource_id"`
	PodTemplateHash string      `json:"pod_template_hash"`
}

// Resolves a (resource, pod-template-hash) pair to the deployment that created
// it. Newest wins when a hash was reused (rollback onto a retained RS).
func (q *Queries) FindDeploymentByRollout(ctx context.Context, arg FindDeploymentByRolloutParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findDeploymentByRollout, arg.ResourceID, arg.PodTemplateHash)
	var deployment_id pgtype.UUID
	err := row.Scan(&deployment_id)
	return deployment_id, err
}

const getActiveDeployment = `-- name: GetActiveDeployment :one
SELECT id, project_id, environment_id, status, error, created, applied, snapshot FROM deployments
 WHERE project_id     = $1
   AND environment_id = $2
   AND status IN ('pending', 'applying')
`

type GetActiveDeploymentParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

// The unique partial index guarantees at most one row per (project, env).
func (q *Queries) GetActiveDeployment(ctx context.Context, arg GetActiveDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeployment, arg.ProjectID, arg.EnvironmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Applied,
		&i.Snapshot,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, project_id, environment_id, status, error, created, applied, snapshot FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Applied,
		&i.Snapshot,
	)
	return i, err
}

const getRolloutHash = `-- name: GetRolloutHash :one
SELECT pod_template_hash
  FROM deployment_rollouts
 WHERE deployment_id = $1 AND resource_id = $2
`

type GetRolloutHashParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	ResourceID   pgtype.UUID `json:"resource_id"`
}

// Resolves a (deployment, resource) pair to the pod-template-hash, for scoping
// logs to a single deployment's pods.
func (q *Queries) GetRolloutHash(ctx context.Context, arg GetRolloutHashParams) (string, error) {
	row := q.db.QueryRow(ctx, getRolloutHash, arg.DeploymentID, arg.ResourceID)
	var pod_template_hash string
	err := row.Scan(&pod_template_hash)
	return pod_template_hash, err
}

const listActiveDeployments = `-- name: ListActiveDeployments :many
SELECT id, project_id, environment_id, status, error, created, applied, snapshot FROM deployments
 WHERE status IN ('pending', 'applying')
 ORDER BY created
`

// Boot recovery: re-fire goroutines for deployments stuck in pending/applying.
func (q *Queries) ListActiveDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listActiveDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Status,
			&i.Error,
			&i.Created,
			&i.Applied,
			&i.Snapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByProject = `-- name: ListDeploymentsByProject :many
SELECT id, project_id, environment_id, status, error, created, applied, snapshot FROM deployments
 WHERE project_id = $1
 ORDER BY created DESC
 LIMIT $2 OFFSET $3
`

type ListDeploymentsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListDeploymentsByProject(ctx context.Context, arg ListDeploymentsByProjectParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Status,
			&i.Error,
			&i.Created,
			&i.Applied,
			&i.Snapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByProjectEnv = `-- name: ListDeploymentsByProjectEnv :many
SELECT id, project_id, environment_id, status, error, created, applied, snapshot FROM deployments
 WHERE project_id     = $1
   AND environment_id = $2
 ORDER BY created DESC
 LIMIT $3 OFFSET $4
`

type ListDeploymentsByProjectEnvParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListDeploymentsByProjectEnv(ctx context.Context, arg ListDeploymentsByProjectEnvParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProjectEnv,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Status,
			&i.Error,
			&i.Created,
			&i.Applied,
			&i.Snapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentApplied = `-- name: MarkDeploymentApplied :one
UPDATE deployments
   SET status = 'applied',
       applied = NOW(),
       error = NULL
 WHERE id = $1
RETURNING id, project_id, environment_id, status, error, created, applied, snapshot
`

func (q *Queries) MarkDeploymentApplied(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, markDeploymentApplied, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Applied,
		&i.Snapshot,
	)
	return i, err
}

const markDeploymentFailed = `-- name: MarkDeploymentFailed :one
UPDATE deployments
   SET status = 'failed',
       error  = $2
 WHERE id = $1
RETURNING id, project_id, environment_id, status, error, created, applied, snapshot
`

type MarkDeploymentFailedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) MarkDeploymentFailed(ctx context.Context, arg MarkDeploymentFailedParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, markDeploymentFailed, arg.ID, arg.Error)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Applied,
		&i.Snapshot,
	)
	return i, err
}

const recordRollout = `-- name: RecordRollout :exec
INSERT INTO deployment_rollouts (deployment_id, resource_id, pod_template_hash)
VALUES ($1, $2, $3)
ON CONFLICT (deployment_id, resource_id)
DO UPDATE SET pod_template_hash = EXCLUDED.pod_template_hash
`

type RecordRolloutParams struct {
	DeploymentID    pgtype.UUID `json:"deployment_id"`
	ResourceID      pgtype.UUID `json:"resource_id"`
	PodTemplateHash string      `json:"pod_template_hash"`
}

// Records the k8s pod-template-hash a deployment produced for a resource, so
// later events on that rollout's RS/Pods can be attributed to the deployment.
func (q *Queries) RecordRollout(ctx context.Context, arg RecordRolloutParams) error {
	_, err := q.db.Exec(ctx, recordRollout, arg.DeploymentID, arg.ResourceID, arg.PodTemplateHash)
	return err
}

const updateDeploymentSnapshot = `-- name: UpdateDeploymentSnapshot :exec
UPDATE deployments
   SET snapshot = $2
 WHERE id = $1
`

type UpdateDeploymentSnapshotParams struct {
	ID       pgtype.UUID `json:"id"`
	Snapshot []byte      `json:"snapshot"`
}

// Used post-Discard to refresh the baseline's snapshot to reflect the
// now-current rows (which have new updated_at timestamps from the writes,
// even though their content matches the original snapshot). Keeps the
// frontend's hasChanges gate in sync after a discard.
func (q *Queries) UpdateDeploymentSnapshot(ctx context.Context, arg UpdateDeploymentSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentSnapshot, arg.ID, arg.Snapshot)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
   SET status = $2,
       error  = $3
 WHERE id = $1
RETURNING id, project_id, environment_id, status, error, created, applied, snapshot
`

type UpdateDeploymentStatusParams struct {
	ID     pgtype.UUID      `json:"id"`
	Status DeploymentStatus `json:"status"`
	Error  *string          `json:"error"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus, arg.ID, arg.Status, arg.Error)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Status,
		&i.Error,
		&i.Created,
		&i.Applied,
		&i.Snapshot,
	)
	return i, err
}
