// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, project_id, status, status_message, payload, checksum)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, seq, status, status_message, payload, checksum, created, applied
`

type CreateDeploymentParams struct {
	ID            pgtype.UUID      `json:"id"`
	ProjectID     pgtype.UUID      `json:"project_id"`
	Status        DeploymentStatus `json:"status"`
	StatusMessage *string          `json:"status_message"`
	Payload       []byte           `json:"payload"`
	Checksum      string           `json:"checksum"`
}

// seq is NULL on insert; the BEFORE INSERT trigger assigns it under the
// per-project advisory lock.
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ID,
		arg.ProjectID,
		arg.Status,
		arg.StatusMessage,
		arg.Payload,
		arg.Checksum,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Status,
		&i.StatusMessage,
		&i.Payload,
		&i.Checksum,
		&i.Created,
		&i.Applied,
	)
	return i, err
}

const getActiveDeployment = `-- name: GetActiveDeployment :one
SELECT id, project_id, seq, status, status_message, payload, checksum, created, applied FROM deployments
 WHERE project_id = $1
   AND status IN ('pending', 'applying')
`

// The unique partial index guarantees at most one row.
func (q *Queries) GetActiveDeployment(ctx context.Context, projectID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeployment, projectID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Status,
		&i.StatusMessage,
		&i.Payload,
		&i.Checksum,
		&i.Created,
		&i.Applied,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, project_id, seq, status, status_message, payload, checksum, created, applied FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Status,
		&i.StatusMessage,
		&i.Payload,
		&i.Checksum,
		&i.Created,
		&i.Applied,
	)
	return i, err
}

const getLatestDeployment = `-- name: GetLatestDeployment :one
SELECT id, project_id, seq, status, status_message, payload, checksum, created, applied FROM deployments
 WHERE project_id = $1
 ORDER BY seq DESC
 LIMIT 1
`

func (q *Queries) GetLatestDeployment(ctx context.Context, projectID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getLatestDeployment, projectID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Status,
		&i.StatusMessage,
		&i.Payload,
		&i.Checksum,
		&i.Created,
		&i.Applied,
	)
	return i, err
}

const listDeploymentsByProject = `-- name: ListDeploymentsByProject :many
SELECT id, project_id, seq, status, status_message, payload, checksum, created, applied FROM deployments
 WHERE project_id = $1
 ORDER BY seq DESC
 LIMIT $2 OFFSET $3
`

type ListDeploymentsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListDeploymentsByProject(ctx context.Context, arg ListDeploymentsByProjectParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Seq,
			&i.Status,
			&i.StatusMessage,
			&i.Payload,
			&i.Checksum,
			&i.Created,
			&i.Applied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentApplied = `-- name: MarkDeploymentApplied :one
UPDATE deployments
   SET status = 'applied', applied = NOW(), status_message = NULL
 WHERE id = $1
RETURNING id, project_id, seq, status, status_message, payload, checksum, created, applied
`

func (q *Queries) MarkDeploymentApplied(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, markDeploymentApplied, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Status,
		&i.StatusMessage,
		&i.Payload,
		&i.Checksum,
		&i.Created,
		&i.Applied,
	)
	return i, err
}

const markDeploymentFailed = `-- name: MarkDeploymentFailed :one
UPDATE deployments
   SET status = 'failed', status_message = $2
 WHERE id = $1
RETURNING id, project_id, seq, status, status_message, payload, checksum, created, applied
`

type MarkDeploymentFailedParams struct {
	ID            pgtype.UUID `json:"id"`
	StatusMessage *string     `json:"status_message"`
}

func (q *Queries) MarkDeploymentFailed(ctx context.Context, arg MarkDeploymentFailedParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, markDeploymentFailed, arg.ID, arg.StatusMessage)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Status,
		&i.StatusMessage,
		&i.Payload,
		&i.Checksum,
		&i.Created,
		&i.Applied,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
   SET status = $2, status_message = $3
 WHERE id = $1
RETURNING id, project_id, seq, status, status_message, payload, checksum, created, applied
`

type UpdateDeploymentStatusParams struct {
	ID            pgtype.UUID      `json:"id"`
	Status        DeploymentStatus `json:"status"`
	StatusMessage *string          `json:"status_message"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus, arg.ID, arg.Status, arg.StatusMessage)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Seq,
		&i.Status,
		&i.StatusMessage,
		&i.Payload,
		&i.Checksum,
		&i.Created,
		&i.Applied,
	)
	return i, err
}
