// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, project_id, slug)
VALUES ($1, $2, $3)
RETURNING id, project_id, slug, created
`

type CreateEnvironmentParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Slug      string      `json:"slug"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ID, arg.ProjectID, arg.Slug)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Created,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, slug, created FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id pgtype.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Created,
	)
	return i, err
}

const getEnvironmentBySlug = `-- name: GetEnvironmentBySlug :one
SELECT id, project_id, slug, created FROM environments
 WHERE project_id = $1 AND slug = $2
`

type GetEnvironmentBySlugParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Slug      string      `json:"slug"`
}

func (q *Queries) GetEnvironmentBySlug(ctx context.Context, arg GetEnvironmentBySlugParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentBySlug, arg.ProjectID, arg.Slug)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Created,
	)
	return i, err
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, slug, created FROM environments
 WHERE project_id = $1
 ORDER BY created
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
