// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeploymentStatus string

const (
	DeploymentStatusPending  DeploymentStatus = "pending"
	DeploymentStatusApplying DeploymentStatus = "applying"
	DeploymentStatusApplied  DeploymentStatus = "applied"
	DeploymentStatusFailed   DeploymentStatus = "failed"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type RoutePathType string

const (
	RoutePathTypePrefix RoutePathType = "prefix"
	RoutePathTypeExact  RoutePathType = "exact"
)

func (e *RoutePathType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoutePathType(s)
	case string:
		*e = RoutePathType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoutePathType: %T", src)
	}
	return nil
}

type NullRoutePathType struct {
	RoutePathType RoutePathType `json:"route_path_type"`
	Valid         bool          `json:"valid"` // Valid is true if RoutePathType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoutePathType) Scan(value interface{}) error {
	if value == nil {
		ns.RoutePathType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoutePathType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoutePathType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoutePathType), nil
}

type VariableScope string

const (
	VariableScopeShared   VariableScope = "shared"
	VariableScopeResource VariableScope = "resource"
)

func (e *VariableScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VariableScope(s)
	case string:
		*e = VariableScope(s)
	default:
		return fmt.Errorf("unsupported scan type for VariableScope: %T", src)
	}
	return nil
}

type NullVariableScope struct {
	VariableScope VariableScope `json:"variable_scope"`
	Valid         bool          `json:"valid"` // Valid is true if VariableScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVariableScope) Scan(value interface{}) error {
	if value == nil {
		ns.VariableScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VariableScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVariableScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VariableScope), nil
}

type Deployment struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Seq           int32              `json:"seq"`
	Status        DeploymentStatus   `json:"status"`
	StatusMessage *string            `json:"status_message"`
	Payload       []byte             `json:"payload"`
	Checksum      string             `json:"checksum"`
	Created       pgtype.Timestamptz `json:"created"`
	Applied       pgtype.Timestamptz `json:"applied"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Created     pgtype.Timestamptz `json:"created"`
	Updated     pgtype.Timestamptz `json:"updated"`
}

type Registry struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Url               string             `json:"url"`
	Username          string             `json:"username"`
	PasswordEncrypted []byte             `json:"password_encrypted"`
	Created           pgtype.Timestamptz `json:"created"`
	Updated           pgtype.Timestamptz `json:"updated"`
}

type Resource struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	PositionX float64            `json:"position_x"`
	PositionY float64            `json:"position_y"`
	Spec      []byte             `json:"spec"`
	Created   pgtype.Timestamptz `json:"created"`
	Updated   pgtype.Timestamptz `json:"updated"`
}

type ResourceVariable struct {
	ProjectID  pgtype.UUID        `json:"project_id"`
	ResourceID pgtype.UUID        `json:"resource_id"`
	VariableID pgtype.UUID        `json:"variable_id"`
	Key        string             `json:"key"`
	Created    pgtype.Timestamptz `json:"created"`
}

type Route struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	ResourceID pgtype.UUID        `json:"resource_id"`
	Domain     string             `json:"domain"`
	Path       string             `json:"path"`
	PathType   RoutePathType      `json:"path_type"`
	Port       int32              `json:"port"`
	Tls        bool               `json:"tls"`
	Config     []byte             `json:"config"`
	Created    pgtype.Timestamptz `json:"created"`
	Updated    pgtype.Timestamptz `json:"updated"`
}

type Variable struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	Scope          *VariableScope     `json:"scope"`
	Key            string             `json:"key"`
	Value          *string            `json:"value"`
	ValueEncrypted []byte             `json:"value_encrypted"`
	Secret         *bool              `json:"secret"`
	Created        pgtype.Timestamptz `json:"created"`
	Updated        pgtype.Timestamptz `json:"updated"`
}
