// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// seq is NULL on insert; the BEFORE INSERT trigger assigns it under the
	// per-project advisory lock.
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreatePlainVariable(ctx context.Context, arg CreatePlainVariableParams) (Variable, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateResourceVariable(ctx context.Context, arg CreateResourceVariableParams) (ResourceVariable, error)
	CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error)
	CreateSecretVariable(ctx context.Context, arg CreateSecretVariableParams) (Variable, error)
	DeleteAllResourceVariables(ctx context.Context, resourceID pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteRegistry(ctx context.Context, id pgtype.UUID) error
	DeleteResource(ctx context.Context, id pgtype.UUID) error
	DeleteResourceVariable(ctx context.Context, arg DeleteResourceVariableParams) error
	DeleteRoute(ctx context.Context, id pgtype.UUID) error
	DeleteVariable(ctx context.Context, id pgtype.UUID) error
	// The unique partial index guarantees at most one row.
	GetActiveDeployment(ctx context.Context, projectID pgtype.UUID) (Deployment, error)
	GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error)
	GetLatestDeployment(ctx context.Context, projectID pgtype.UUID) (Deployment, error)
	GetOwnedVariableByKey(ctx context.Context, arg GetOwnedVariableByKeyParams) (Variable, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetRegistry(ctx context.Context, id pgtype.UUID) (Registry, error)
	GetRegistryByName(ctx context.Context, name string) (Registry, error)
	GetResource(ctx context.Context, id pgtype.UUID) (Resource, error)
	GetResourceByName(ctx context.Context, arg GetResourceByNameParams) (Resource, error)
	GetRoute(ctx context.Context, id pgtype.UUID) (Route, error)
	GetVariable(ctx context.Context, id pgtype.UUID) (Variable, error)
	ListDeploymentsByProject(ctx context.Context, arg ListDeploymentsByProjectParams) ([]Deployment, error)
	ListImportsOfVariable(ctx context.Context, variableID pgtype.UUID) ([]ResourceVariable, error)
	ListOwnedVariables(ctx context.Context, arg ListOwnedVariablesParams) ([]Variable, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListRegistries(ctx context.Context) ([]Registry, error)
	ListResourceImports(ctx context.Context, resourceID pgtype.UUID) ([]ResourceVariable, error)
	ListResourcesByProject(ctx context.Context, projectID pgtype.UUID) ([]Resource, error)
	ListRoutesByProject(ctx context.Context, projectID pgtype.UUID) ([]Route, error)
	ListRoutesByResource(ctx context.Context, resourceID pgtype.UUID) ([]Route, error)
	ListVariablesByProject(ctx context.Context, projectID pgtype.UUID) ([]Variable, error)
	LookupRoute(ctx context.Context, arg LookupRouteParams) (Route, error)
	MarkDeploymentApplied(ctx context.Context, id pgtype.UUID) (Deployment, error)
	MarkDeploymentFailed(ctx context.Context, arg MarkDeploymentFailedParams) (Deployment, error)
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error)
	UpdatePlainVariableValue(ctx context.Context, arg UpdatePlainVariableValueParams) (Variable, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateResourcePosition(ctx context.Context, arg UpdateResourcePositionParams) error
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error)
	UpdateSecretVariableValue(ctx context.Context, arg UpdateSecretVariableValueParams) (Variable, error)
	UpdateVariableKey(ctx context.Context, arg UpdateVariableKeyParams) (Variable, error)
}

var _ Querier = (*Queries)(nil)
