// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistry = `-- name: CreateRegistry :one
INSERT INTO registries (id, name, url, username, password_encrypted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, url, username, password_encrypted, created, updated
`

type CreateRegistryParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Url               string      `json:"url"`
	Username          string      `json:"username"`
	PasswordEncrypted []byte      `json:"password_encrypted"`
}

func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, createRegistry,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Username,
		arg.PasswordEncrypted,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteRegistry = `-- name: DeleteRegistry :exec
DELETE FROM registries WHERE id = $1
`

func (q *Queries) DeleteRegistry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegistry, id)
	return err
}

const getRegistry = `-- name: GetRegistry :one
SELECT id, name, url, username, password_encrypted, created, updated FROM registries WHERE id = $1
`

func (q *Queries) GetRegistry(ctx context.Context, id pgtype.UUID) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistry, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getRegistryByName = `-- name: GetRegistryByName :one
SELECT id, name, url, username, password_encrypted, created, updated FROM registries WHERE name = $1
`

func (q *Queries) GetRegistryByName(ctx context.Context, name string) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistryByName, name)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listRegistries = `-- name: ListRegistries :many
SELECT id, name, url, username, password_encrypted, created, updated FROM registries ORDER BY name
`

func (q *Queries) ListRegistries(ctx context.Context) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registry
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Username,
			&i.PasswordEncrypted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistry = `-- name: UpdateRegistry :one
UPDATE registries
   SET name = $2, url = $3, username = $4, password_encrypted = $5
 WHERE id = $1
RETURNING id, name, url, username, password_encrypted, created, updated
`

type UpdateRegistryParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Url               string      `json:"url"`
	Username          string      `json:"username"`
	PasswordEncrypted []byte      `json:"password_encrypted"`
}

func (q *Queries) UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, updateRegistry,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Username,
		arg.PasswordEncrypted,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
