// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_variables.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResourceVariable = `-- name: CreateResourceVariable :one
INSERT INTO resource_variables (project_id, environment_id, resource_id, variable_id, key)
VALUES ($1, $2, $3, $4, $5)
RETURNING project_id, environment_id, resource_id, variable_id, key, created
`

type CreateResourceVariableParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ResourceID    pgtype.UUID `json:"resource_id"`
	VariableID    pgtype.UUID `json:"variable_id"`
	Key           string      `json:"key"`
}

func (q *Queries) CreateResourceVariable(ctx context.Context, arg CreateResourceVariableParams) (ResourceVariable, error) {
	row := q.db.QueryRow(ctx, createResourceVariable,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ResourceID,
		arg.VariableID,
		arg.Key,
	)
	var i ResourceVariable
	err := row.Scan(
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.VariableID,
		&i.Key,
		&i.Created,
	)
	return i, err
}

const deleteAllResourceVariables = `-- name: DeleteAllResourceVariables :exec
DELETE FROM resource_variables WHERE resource_id = $1
`

func (q *Queries) DeleteAllResourceVariables(ctx context.Context, resourceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllResourceVariables, resourceID)
	return err
}

const deleteResourceVariable = `-- name: DeleteResourceVariable :exec
DELETE FROM resource_variables
 WHERE resource_id    = $1
   AND environment_id = $2
   AND key            = $3
`

type DeleteResourceVariableParams struct {
	ResourceID    pgtype.UUID `json:"resource_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Key           string      `json:"key"`
}

func (q *Queries) DeleteResourceVariable(ctx context.Context, arg DeleteResourceVariableParams) error {
	_, err := q.db.Exec(ctx, deleteResourceVariable, arg.ResourceID, arg.EnvironmentID, arg.Key)
	return err
}

const listImportsOfVariable = `-- name: ListImportsOfVariable :many
SELECT project_id, environment_id, resource_id, variable_id, key, created FROM resource_variables
 WHERE variable_id = $1
 ORDER BY resource_id, key
`

func (q *Queries) ListImportsOfVariable(ctx context.Context, variableID pgtype.UUID) ([]ResourceVariable, error) {
	rows, err := q.db.Query(ctx, listImportsOfVariable, variableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceVariable
	for rows.Next() {
		var i ResourceVariable
		if err := rows.Scan(
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ResourceID,
			&i.VariableID,
			&i.Key,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceImports = `-- name: ListResourceImports :many
SELECT project_id, environment_id, resource_id, variable_id, key, created FROM resource_variables
 WHERE resource_id = $1 AND environment_id = $2
 ORDER BY key
`

type ListResourceImportsParams struct {
	ResourceID    pgtype.UUID `json:"resource_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

func (q *Queries) ListResourceImports(ctx context.Context, arg ListResourceImportsParams) ([]ResourceVariable, error) {
	rows, err := q.db.Query(ctx, listResourceImports, arg.ResourceID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceVariable
	for rows.Next() {
		var i ResourceVariable
		if err := rows.Scan(
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ResourceID,
			&i.VariableID,
			&i.Key,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceImportsByEnv = `-- name: ListResourceImportsByEnv :many
SELECT project_id, environment_id, resource_id, variable_id, key, created FROM resource_variables
 WHERE project_id = $1 AND environment_id = $2
 ORDER BY resource_id, key
`

type ListResourceImportsByEnvParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

func (q *Queries) ListResourceImportsByEnv(ctx context.Context, arg ListResourceImportsByEnvParams) ([]ResourceVariable, error) {
	rows, err := q.db.Query(ctx, listResourceImportsByEnv, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceVariable
	for rows.Next() {
		var i ResourceVariable
		if err := rows.Scan(
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ResourceID,
			&i.VariableID,
			&i.Key,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
