// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_variables.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResourceVariable = `-- name: CreateResourceVariable :one
INSERT INTO resource_variables (project_id, resource_id, variable_id, key)
VALUES ($1, $2, $3, $4)
RETURNING project_id, resource_id, variable_id, key, created
`

type CreateResourceVariableParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	ResourceID pgtype.UUID `json:"resource_id"`
	VariableID pgtype.UUID `json:"variable_id"`
	Key        string      `json:"key"`
}

func (q *Queries) CreateResourceVariable(ctx context.Context, arg CreateResourceVariableParams) (ResourceVariable, error) {
	row := q.db.QueryRow(ctx, createResourceVariable,
		arg.ProjectID,
		arg.ResourceID,
		arg.VariableID,
		arg.Key,
	)
	var i ResourceVariable
	err := row.Scan(
		&i.ProjectID,
		&i.ResourceID,
		&i.VariableID,
		&i.Key,
		&i.Created,
	)
	return i, err
}

const deleteAllResourceVariables = `-- name: DeleteAllResourceVariables :exec
DELETE FROM resource_variables WHERE resource_id = $1
`

func (q *Queries) DeleteAllResourceVariables(ctx context.Context, resourceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllResourceVariables, resourceID)
	return err
}

const deleteResourceVariable = `-- name: DeleteResourceVariable :exec
DELETE FROM resource_variables
 WHERE resource_id = $1 AND key = $2
`

type DeleteResourceVariableParams struct {
	ResourceID pgtype.UUID `json:"resource_id"`
	Key        string      `json:"key"`
}

func (q *Queries) DeleteResourceVariable(ctx context.Context, arg DeleteResourceVariableParams) error {
	_, err := q.db.Exec(ctx, deleteResourceVariable, arg.ResourceID, arg.Key)
	return err
}

const listImportsOfVariable = `-- name: ListImportsOfVariable :many
SELECT project_id, resource_id, variable_id, key, created FROM resource_variables
 WHERE variable_id = $1
 ORDER BY resource_id, key
`

func (q *Queries) ListImportsOfVariable(ctx context.Context, variableID pgtype.UUID) ([]ResourceVariable, error) {
	rows, err := q.db.Query(ctx, listImportsOfVariable, variableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceVariable
	for rows.Next() {
		var i ResourceVariable
		if err := rows.Scan(
			&i.ProjectID,
			&i.ResourceID,
			&i.VariableID,
			&i.Key,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceImports = `-- name: ListResourceImports :many
SELECT project_id, resource_id, variable_id, key, created FROM resource_variables
 WHERE resource_id = $1
 ORDER BY key
`

func (q *Queries) ListResourceImports(ctx context.Context, resourceID pgtype.UUID) ([]ResourceVariable, error) {
	rows, err := q.db.Query(ctx, listResourceImports, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceVariable
	for rows.Next() {
		var i ResourceVariable
		if err := rows.Scan(
			&i.ProjectID,
			&i.ResourceID,
			&i.VariableID,
			&i.Key,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
