// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (id, project_id, name, kind, position_x, position_y, spec)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, kind, position_x, position_y, spec, created, updated
`

type CreateResourceParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Kind      string      `json:"kind"`
	PositionX float64     `json:"position_x"`
	PositionY float64     `json:"position_y"`
	Spec      []byte      `json:"spec"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.PositionX,
		arg.PositionY,
		arg.Spec,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.PositionX,
		&i.PositionY,
		&i.Spec,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, project_id, name, kind, position_x, position_y, spec, created, updated FROM resources WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id pgtype.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.PositionX,
		&i.PositionY,
		&i.Spec,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getResourceByName = `-- name: GetResourceByName :one
SELECT id, project_id, name, kind, position_x, position_y, spec, created, updated FROM resources WHERE project_id = $1 AND name = $2
`

type GetResourceByNameParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) GetResourceByName(ctx context.Context, arg GetResourceByNameParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByName, arg.ProjectID, arg.Name)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.PositionX,
		&i.PositionY,
		&i.Spec,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listResourcesByProject = `-- name: ListResourcesByProject :many
SELECT id, project_id, name, kind, position_x, position_y, spec, created, updated FROM resources WHERE project_id = $1 ORDER BY created
`

func (q *Queries) ListResourcesByProject(ctx context.Context, projectID pgtype.UUID) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.PositionX,
			&i.PositionY,
			&i.Spec,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
   SET name = $2, kind = $3, spec = $4
 WHERE id = $1
RETURNING id, project_id, name, kind, position_x, position_y, spec, created, updated
`

type UpdateResourceParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Kind string      `json:"kind"`
	Spec []byte      `json:"spec"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Spec,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.PositionX,
		&i.PositionY,
		&i.Spec,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateResourcePosition = `-- name: UpdateResourcePosition :exec
UPDATE resources
   SET position_x = $2, position_y = $3
 WHERE id = $1
`

type UpdateResourcePositionParams struct {
	ID        pgtype.UUID `json:"id"`
	PositionX float64     `json:"position_x"`
	PositionY float64     `json:"position_y"`
}

func (q *Queries) UpdateResourcePosition(ctx context.Context, arg UpdateResourcePositionParams) error {
	_, err := q.db.Exec(ctx, updateResourcePosition, arg.ID, arg.PositionX, arg.PositionY)
	return err
}
