// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (id, project_id, resource_id, domain, path, path_type, port, tls, config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, resource_id, domain, path, path_type, port, tls, config, created, updated
`

type CreateRouteParams struct {
	ID         pgtype.UUID   `json:"id"`
	ProjectID  pgtype.UUID   `json:"project_id"`
	ResourceID pgtype.UUID   `json:"resource_id"`
	Domain     string        `json:"domain"`
	Path       string        `json:"path"`
	PathType   RoutePathType `json:"path_type"`
	Port       int32         `json:"port"`
	Tls        bool          `json:"tls"`
	Config     []byte        `json:"config"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.ID,
		arg.ProjectID,
		arg.ResourceID,
		arg.Domain,
		arg.Path,
		arg.PathType,
		arg.Port,
		arg.Tls,
		arg.Config,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceID,
		&i.Domain,
		&i.Path,
		&i.PathType,
		&i.Port,
		&i.Tls,
		&i.Config,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, project_id, resource_id, domain, path, path_type, port, tls, config, created, updated FROM routes WHERE id = $1
`

func (q *Queries) GetRoute(ctx context.Context, id pgtype.UUID) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceID,
		&i.Domain,
		&i.Path,
		&i.PathType,
		&i.Port,
		&i.Tls,
		&i.Config,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listRoutesByProject = `-- name: ListRoutesByProject :many
SELECT id, project_id, resource_id, domain, path, path_type, port, tls, config, created, updated FROM routes WHERE project_id = $1 ORDER BY domain, path
`

func (q *Queries) ListRoutesByProject(ctx context.Context, projectID pgtype.UUID) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ResourceID,
			&i.Domain,
			&i.Path,
			&i.PathType,
			&i.Port,
			&i.Tls,
			&i.Config,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByResource = `-- name: ListRoutesByResource :many
SELECT id, project_id, resource_id, domain, path, path_type, port, tls, config, created, updated FROM routes WHERE resource_id = $1 ORDER BY domain, path
`

func (q *Queries) ListRoutesByResource(ctx context.Context, resourceID pgtype.UUID) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ResourceID,
			&i.Domain,
			&i.Path,
			&i.PathType,
			&i.Port,
			&i.Tls,
			&i.Config,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupRoute = `-- name: LookupRoute :one
SELECT id, project_id, resource_id, domain, path, path_type, port, tls, config, created, updated FROM routes
 WHERE domain = $1 AND path = $2 AND path_type = $3
`

type LookupRouteParams struct {
	Domain   string        `json:"domain"`
	Path     string        `json:"path"`
	PathType RoutePathType `json:"path_type"`
}

func (q *Queries) LookupRoute(ctx context.Context, arg LookupRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, lookupRoute, arg.Domain, arg.Path, arg.PathType)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceID,
		&i.Domain,
		&i.Path,
		&i.PathType,
		&i.Port,
		&i.Tls,
		&i.Config,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes
   SET domain    = $2,
       path      = $3,
       path_type = $4,
       port      = $5,
       tls       = $6,
       config    = $7
 WHERE id = $1
RETURNING id, project_id, resource_id, domain, path, path_type, port, tls, config, created, updated
`

type UpdateRouteParams struct {
	ID       pgtype.UUID   `json:"id"`
	Domain   string        `json:"domain"`
	Path     string        `json:"path"`
	PathType RoutePathType `json:"path_type"`
	Port     int32         `json:"port"`
	Tls      bool          `json:"tls"`
	Config   []byte        `json:"config"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.ID,
		arg.Domain,
		arg.Path,
		arg.PathType,
		arg.Port,
		arg.Tls,
		arg.Config,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ResourceID,
		&i.Domain,
		&i.Path,
		&i.PathType,
		&i.Port,
		&i.Tls,
		&i.Config,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
