// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSourcesInDomain = `-- name: CountSourcesInDomain :one
SELECT COUNT(*) FROM sources WHERE domain = $1
`

func (q *Queries) CountSourcesInDomain(ctx context.Context, domain SourceDomain) (int64, error) {
	row := q.db.QueryRow(ctx, countSourcesInDomain, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, kind, domain, name, is_default, config, auth_encrypted)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, kind, domain, name, is_default, config, auth_encrypted, created, updated
`

type CreateSourceParams struct {
	ID            pgtype.UUID  `json:"id"`
	Kind          SourceKind   `json:"kind"`
	Domain        SourceDomain `json:"domain"`
	Name          string       `json:"name"`
	IsDefault     bool         `json:"is_default"`
	Config        []byte       `json:"config"`
	AuthEncrypted []byte       `json:"auth_encrypted"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.Kind,
		arg.Domain,
		arg.Name,
		arg.IsDefault,
		arg.Config,
		arg.AuthEncrypted,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getDefaultSource = `-- name: GetDefaultSource :one
SELECT id, kind, domain, name, is_default, config, auth_encrypted, created, updated FROM sources WHERE domain = $1 AND is_default = true
`

func (q *Queries) GetDefaultSource(ctx context.Context, domain SourceDomain) (Source, error) {
	row := q.db.QueryRow(ctx, getDefaultSource, domain)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, kind, domain, name, is_default, config, auth_encrypted, created, updated FROM sources WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, kind, domain, name, is_default, config, auth_encrypted, created, updated FROM sources ORDER BY name
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Domain,
			&i.Name,
			&i.IsDefault,
			&i.Config,
			&i.AuthEncrypted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByDomain = `-- name: ListSourcesByDomain :many
SELECT id, kind, domain, name, is_default, config, auth_encrypted, created, updated FROM sources WHERE domain = $1 ORDER BY name
`

func (q *Queries) ListSourcesByDomain(ctx context.Context, domain SourceDomain) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Domain,
			&i.Name,
			&i.IsDefault,
			&i.Config,
			&i.AuthEncrypted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultSource = `-- name: SetDefaultSource :exec
UPDATE sources
   SET is_default = (id = $1)
 WHERE domain = $2
`

type SetDefaultSourceParams struct {
	ID     pgtype.UUID  `json:"id"`
	Domain SourceDomain `json:"domain"`
}

// Atomically flips is_default for one row in the domain and clears it on
// the rest. The single statement is one SQL transaction.
func (q *Queries) SetDefaultSource(ctx context.Context, arg SetDefaultSourceParams) error {
	_, err := q.db.Exec(ctx, setDefaultSource, arg.ID, arg.Domain)
	return err
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
   SET name = $2, config = $3, auth_encrypted = $4
 WHERE id = $1
RETURNING id, kind, domain, name, is_default, config, auth_encrypted, created, updated
`

type UpdateSourceParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Config        []byte      `json:"config"`
	AuthEncrypted []byte      `json:"auth_encrypted"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.AuthEncrypted,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
