// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultSource = `-- name: ClearDefaultSource :exec
UPDATE sources
   SET is_default = false
 WHERE domain = $1 AND id <> $2 AND is_default = true
`

type ClearDefaultSourceParams struct {
	Domain SourceDomain `json:"domain"`
	ID     pgtype.UUID  `json:"id"`
}

// Step 1 of promotion: clear is_default on every other row in the
// domain. Paired w/ SetDefaultTrue under a single Go transaction so the
// partial unique index on (domain) WHERE is_default = true doesn't fire
// mid-row of a multi-row UPDATE.
func (q *Queries) ClearDefaultSource(ctx context.Context, arg ClearDefaultSourceParams) error {
	_, err := q.db.Exec(ctx, clearDefaultSource, arg.Domain, arg.ID)
	return err
}

const countSourcesInDomain = `-- name: CountSourcesInDomain :one
SELECT COUNT(*) FROM sources WHERE domain = $1
`

func (q *Queries) CountSourcesInDomain(ctx context.Context, domain SourceDomain) (int64, error) {
	row := q.db.QueryRow(ctx, countSourcesInDomain, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, kind, domain, name, is_default, config, auth_encrypted)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, kind, domain, name, is_default, config, auth_encrypted, created, updated, provisioned
`

type CreateSourceParams struct {
	ID            pgtype.UUID  `json:"id"`
	Kind          SourceKind   `json:"kind"`
	Domain        SourceDomain `json:"domain"`
	Name          string       `json:"name"`
	IsDefault     bool         `json:"is_default"`
	Config        []byte       `json:"config"`
	AuthEncrypted []byte       `json:"auth_encrypted"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.Kind,
		arg.Domain,
		arg.Name,
		arg.IsDefault,
		arg.Config,
		arg.AuthEncrypted,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
		&i.Provisioned,
	)
	return i, err
}

const deleteProvisionedSourcesNotIn = `-- name: DeleteProvisionedSourcesNotIn :exec
DELETE FROM sources
 WHERE provisioned = true
   AND NOT (name = ANY($1::text[]))
`

// Sync delete: drop provisioned rows whose name is absent from the
// current config snapshot. Empty $1 (no provisioned entries in config)
// deletes every provisioned row.
func (q *Queries) DeleteProvisionedSourcesNotIn(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteProvisionedSourcesNotIn, dollar_1)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getDefaultSource = `-- name: GetDefaultSource :one
SELECT id, kind, domain, name, is_default, config, auth_encrypted, created, updated, provisioned FROM sources WHERE domain = $1 AND is_default = true
`

func (q *Queries) GetDefaultSource(ctx context.Context, domain SourceDomain) (Source, error) {
	row := q.db.QueryRow(ctx, getDefaultSource, domain)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
		&i.Provisioned,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, kind, domain, name, is_default, config, auth_encrypted, created, updated, provisioned FROM sources WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
		&i.Provisioned,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, kind, domain, name, is_default, config, auth_encrypted, created, updated, provisioned FROM sources ORDER BY name
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Domain,
			&i.Name,
			&i.IsDefault,
			&i.Config,
			&i.AuthEncrypted,
			&i.Created,
			&i.Updated,
			&i.Provisioned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByDomain = `-- name: ListSourcesByDomain :many
SELECT id, kind, domain, name, is_default, config, auth_encrypted, created, updated, provisioned FROM sources WHERE domain = $1 ORDER BY name
`

func (q *Queries) ListSourcesByDomain(ctx context.Context, domain SourceDomain) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Domain,
			&i.Name,
			&i.IsDefault,
			&i.Config,
			&i.AuthEncrypted,
			&i.Created,
			&i.Updated,
			&i.Provisioned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultTrue = `-- name: SetDefaultTrue :exec
UPDATE sources
   SET is_default = true
 WHERE id = $1
`

// Step 2: mark the target row as default. Must run after
// ClearDefaultSource inside the same transaction.
func (q *Queries) SetDefaultTrue(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setDefaultTrue, id)
	return err
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
   SET name = $2, config = $3, auth_encrypted = $4
 WHERE id = $1
RETURNING id, kind, domain, name, is_default, config, auth_encrypted, created, updated, provisioned
`

type UpdateSourceParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Config        []byte      `json:"config"`
	AuthEncrypted []byte      `json:"auth_encrypted"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.AuthEncrypted,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
		&i.Provisioned,
	)
	return i, err
}

const upsertProvisionedSource = `-- name: UpsertProvisionedSource :one
INSERT INTO sources (id, kind, domain, name, is_default, config, auth_encrypted, provisioned)
VALUES ($1, $2, $3, $4, $5, $6, $7, true)
ON CONFLICT (name) DO UPDATE
  SET kind           = EXCLUDED.kind,
      domain         = EXCLUDED.domain,
      config         = EXCLUDED.config,
      auth_encrypted = EXCLUDED.auth_encrypted,
      provisioned    = true
RETURNING id, kind, domain, name, is_default, config, auth_encrypted, created, updated, provisioned
`

type UpsertProvisionedSourceParams struct {
	ID            pgtype.UUID  `json:"id"`
	Kind          SourceKind   `json:"kind"`
	Domain        SourceDomain `json:"domain"`
	Name          string       `json:"name"`
	IsDefault     bool         `json:"is_default"`
	Config        []byte       `json:"config"`
	AuthEncrypted []byte       `json:"auth_encrypted"`
}

// Idempotent write for sources sourced from /etc/vyft/provisioning. Match
// by name (unique) so the deterministic ID from the loader is recorded
// on first insert and stable across restarts. is_default is left alone
// on update so an operator's PromoteDefault choice survives reloads.
func (q *Queries) UpsertProvisionedSource(ctx context.Context, arg UpsertProvisionedSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, upsertProvisionedSource,
		arg.ID,
		arg.Kind,
		arg.Domain,
		arg.Name,
		arg.IsDefault,
		arg.Config,
		arg.AuthEncrypted,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Domain,
		&i.Name,
		&i.IsDefault,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
		&i.Provisioned,
	)
	return i, err
}
