// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, kind, name, config, auth_encrypted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kind, name, config, auth_encrypted, created, updated
`

type CreateSourceParams struct {
	ID            pgtype.UUID `json:"id"`
	Kind          SourceKind  `json:"kind"`
	Name          string      `json:"name"`
	Config        []byte      `json:"config"`
	AuthEncrypted []byte      `json:"auth_encrypted"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Config,
		arg.AuthEncrypted,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const deleteSourceDefault = `-- name: DeleteSourceDefault :exec
DELETE FROM source_defaults WHERE domain = $1
`

func (q *Queries) DeleteSourceDefault(ctx context.Context, domain SourceDomain) error {
	_, err := q.db.Exec(ctx, deleteSourceDefault, domain)
	return err
}

const getSource = `-- name: GetSource :one
SELECT id, kind, name, config, auth_encrypted, created, updated FROM sources WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getSourceDefault = `-- name: GetSourceDefault :one
SELECT s.id, s.kind, s.name, s.config, s.auth_encrypted, s.created, s.updated
  FROM source_defaults d
  JOIN sources s ON s.id = d.source_id
 WHERE d.domain = $1
`

func (q *Queries) GetSourceDefault(ctx context.Context, domain SourceDomain) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceDefault, domain)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, kind, name, config, auth_encrypted, created, updated FROM sources ORDER BY name
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Config,
			&i.AuthEncrypted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSourceDefault = `-- name: SetSourceDefault :exec
INSERT INTO source_defaults (domain, source_id)
VALUES ($1, $2)
ON CONFLICT (domain) DO UPDATE
   SET source_id = EXCLUDED.source_id,
       updated = NOW()
`

type SetSourceDefaultParams struct {
	Domain   SourceDomain `json:"domain"`
	SourceID pgtype.UUID  `json:"source_id"`
}

func (q *Queries) SetSourceDefault(ctx context.Context, arg SetSourceDefaultParams) error {
	_, err := q.db.Exec(ctx, setSourceDefault, arg.Domain, arg.SourceID)
	return err
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
   SET name = $2, config = $3, auth_encrypted = $4
 WHERE id = $1
RETURNING id, kind, name, config, auth_encrypted, created, updated
`

type UpdateSourceParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Config        []byte      `json:"config"`
	AuthEncrypted []byte      `json:"auth_encrypted"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.AuthEncrypted,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Config,
		&i.AuthEncrypted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
