// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variables.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlainVariable = `-- name: CreatePlainVariable :one
INSERT INTO variables (id, project_id, environment_id, resource_id, key, value)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated
`

type CreatePlainVariableParams struct {
	ID            pgtype.UUID `json:"id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ResourceID    pgtype.UUID `json:"resource_id"`
	Key           string      `json:"key"`
	Value         *string     `json:"value"`
}

func (q *Queries) CreatePlainVariable(ctx context.Context, arg CreatePlainVariableParams) (Variable, error) {
	row := q.db.QueryRow(ctx, createPlainVariable,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ResourceID,
		arg.Key,
		arg.Value,
	)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.Scope,
		&i.Key,
		&i.Value,
		&i.ValueEncrypted,
		&i.Secret,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createSecretVariable = `-- name: CreateSecretVariable :one
INSERT INTO variables (id, project_id, environment_id, resource_id, key, value_encrypted)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated
`

type CreateSecretVariableParams struct {
	ID             pgtype.UUID `json:"id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
	ResourceID     pgtype.UUID `json:"resource_id"`
	Key            string      `json:"key"`
	ValueEncrypted []byte      `json:"value_encrypted"`
}

func (q *Queries) CreateSecretVariable(ctx context.Context, arg CreateSecretVariableParams) (Variable, error) {
	row := q.db.QueryRow(ctx, createSecretVariable,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ResourceID,
		arg.Key,
		arg.ValueEncrypted,
	)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.Scope,
		&i.Key,
		&i.Value,
		&i.ValueEncrypted,
		&i.Secret,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteVariable = `-- name: DeleteVariable :exec
DELETE FROM variables WHERE id = $1
`

func (q *Queries) DeleteVariable(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariable, id)
	return err
}

const getOwnedVariableByKey = `-- name: GetOwnedVariableByKey :one
SELECT id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated FROM variables
 WHERE project_id     = $1
   AND environment_id = $2
   AND resource_id    = $3
   AND key            = $4
`

type GetOwnedVariableByKeyParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ResourceID    pgtype.UUID `json:"resource_id"`
	Key           string      `json:"key"`
}

func (q *Queries) GetOwnedVariableByKey(ctx context.Context, arg GetOwnedVariableByKeyParams) (Variable, error) {
	row := q.db.QueryRow(ctx, getOwnedVariableByKey,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ResourceID,
		arg.Key,
	)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.Scope,
		&i.Key,
		&i.Value,
		&i.ValueEncrypted,
		&i.Secret,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getVariable = `-- name: GetVariable :one
SELECT id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated FROM variables WHERE id = $1
`

func (q *Queries) GetVariable(ctx context.Context, id pgtype.UUID) (Variable, error) {
	row := q.db.QueryRow(ctx, getVariable, id)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.Scope,
		&i.Key,
		&i.Value,
		&i.ValueEncrypted,
		&i.Secret,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listOwnedVariables = `-- name: ListOwnedVariables :many
SELECT id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated FROM variables
 WHERE project_id = $1 AND environment_id = $2 AND resource_id = $3
 ORDER BY key
`

type ListOwnedVariablesParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ResourceID    pgtype.UUID `json:"resource_id"`
}

func (q *Queries) ListOwnedVariables(ctx context.Context, arg ListOwnedVariablesParams) ([]Variable, error) {
	rows, err := q.db.Query(ctx, listOwnedVariables, arg.ProjectID, arg.EnvironmentID, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variable
	for rows.Next() {
		var i Variable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ResourceID,
			&i.Scope,
			&i.Key,
			&i.Value,
			&i.ValueEncrypted,
			&i.Secret,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariablesByProject = `-- name: ListVariablesByProject :many
SELECT id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated FROM variables WHERE project_id = $1 ORDER BY scope, key
`

func (q *Queries) ListVariablesByProject(ctx context.Context, projectID pgtype.UUID) ([]Variable, error) {
	rows, err := q.db.Query(ctx, listVariablesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variable
	for rows.Next() {
		var i Variable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ResourceID,
			&i.Scope,
			&i.Key,
			&i.Value,
			&i.ValueEncrypted,
			&i.Secret,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariablesByProjectEnv = `-- name: ListVariablesByProjectEnv :many
SELECT id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated FROM variables
 WHERE project_id = $1 AND environment_id = $2
 ORDER BY scope, key
`

type ListVariablesByProjectEnvParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

func (q *Queries) ListVariablesByProjectEnv(ctx context.Context, arg ListVariablesByProjectEnvParams) ([]Variable, error) {
	rows, err := q.db.Query(ctx, listVariablesByProjectEnv, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variable
	for rows.Next() {
		var i Variable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ResourceID,
			&i.Scope,
			&i.Key,
			&i.Value,
			&i.ValueEncrypted,
			&i.Secret,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlainVariableValue = `-- name: UpdatePlainVariableValue :one
UPDATE variables
   SET value = $2, value_encrypted = NULL
 WHERE id = $1
RETURNING id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated
`

type UpdatePlainVariableValueParams struct {
	ID    pgtype.UUID `json:"id"`
	Value *string     `json:"value"`
}

func (q *Queries) UpdatePlainVariableValue(ctx context.Context, arg UpdatePlainVariableValueParams) (Variable, error) {
	row := q.db.QueryRow(ctx, updatePlainVariableValue, arg.ID, arg.Value)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.Scope,
		&i.Key,
		&i.Value,
		&i.ValueEncrypted,
		&i.Secret,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateSecretVariableValue = `-- name: UpdateSecretVariableValue :one
UPDATE variables
   SET value_encrypted = $2, value = NULL
 WHERE id = $1
RETURNING id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated
`

type UpdateSecretVariableValueParams struct {
	ID             pgtype.UUID `json:"id"`
	ValueEncrypted []byte      `json:"value_encrypted"`
}

func (q *Queries) UpdateSecretVariableValue(ctx context.Context, arg UpdateSecretVariableValueParams) (Variable, error) {
	row := q.db.QueryRow(ctx, updateSecretVariableValue, arg.ID, arg.ValueEncrypted)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.Scope,
		&i.Key,
		&i.Value,
		&i.ValueEncrypted,
		&i.Secret,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateVariableKey = `-- name: UpdateVariableKey :one
UPDATE variables SET key = $2 WHERE id = $1 RETURNING id, project_id, environment_id, resource_id, scope, key, value, value_encrypted, secret, created, updated
`

type UpdateVariableKeyParams struct {
	ID  pgtype.UUID `json:"id"`
	Key string      `json:"key"`
}

func (q *Queries) UpdateVariableKey(ctx context.Context, arg UpdateVariableKeyParams) (Variable, error) {
	row := q.db.QueryRow(ctx, updateVariableKey, arg.ID, arg.Key)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.Scope,
		&i.Key,
		&i.Value,
		&i.ValueEncrypted,
		&i.Secret,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
