import assert from "node:assert";
import { test } from "../src/index.ts";

// =============================================================================
// AUTO-GENERATED SECRETS
// =============================================================================

export const secretAutoGenerated = test({
  name: "secret is auto-generated on deploy",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-autogen",
  },

  config: `
    import { config } from "vyft";

    export const apiKey = config("api-key", { secret: true });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    // Deploy without setting secret - should auto-generate
    await vyft.deploy();

    const value = await vyft.config.get("api-key");
    assert(value, "should have generated secret");
    assert(value.length >= 32, "secret should be at least 32 chars");
  },
});

export const secretPreservedOnRedeploy = test({
  name: "generated secret preserved on redeploy",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-preserve",
  },

  config: `
    import { service, config } from "vyft";

    export const app = service("app", {
      image: "nginx:alpine",
      env: {
        SECRET: config("my-secret", { secret: true }),
      },
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    // First deploy generates secret
    await vyft.deploy();
    const initial = await vyft.config.get("my-secret");

    // Redeploy should preserve
    await vyft.deploy();
    const after = await vyft.config.get("my-secret");

    assert.strictEqual(initial, after, "secret should be preserved");
  },
});

// =============================================================================
// SECRET WITH CUSTOM LENGTH
// =============================================================================

export const secretCustomLength = test({
  name: "secret with custom length",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-length",
  },

  config: `
    import { config } from "vyft";

    export const shortSecret = config("short", { secret: true, length: 16 });
    export const longSecret = config("long", { secret: true, length: 64 });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    await vyft.deploy();

    const short = await vyft.config.get("short");
    const long = await vyft.config.get("long");

    assert(short, "should have short secret");
    assert(long, "should have long secret");
    assert.strictEqual(short.length, 16, "short should be 16 chars");
    assert.strictEqual(long.length, 64, "long should be 64 chars");
  },
});

// =============================================================================
// SECRET WITH CUSTOM ALPHABET
// =============================================================================

export const secretNumericOnly = test({
  name: "secret with numeric alphabet",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-numeric",
  },

  config: `
    import { config } from "vyft";

    export const pin = config("pin", {
      secret: true,
      length: 6,
      alphabet: "0123456789",
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    await vyft.deploy();

    const pin = await vyft.config.get("pin");
    assert(pin, "should have pin");
    assert.strictEqual(pin.length, 6, "should be 6 digits");
    assert(/^\d+$/.test(pin), "should only contain digits");
  },
});

export const secretAlphanumericOnly = test({
  name: "secret with alphanumeric alphabet",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-alphanum",
  },

  config: `
    import { config } from "vyft";

    export const code = config("code", {
      secret: true,
      length: 8,
      alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    await vyft.deploy();

    const code = await vyft.config.get("code");
    assert(code, "should have code");
    assert.strictEqual(code.length, 8);
    assert(/^[A-Z0-9]+$/.test(code), "should only contain uppercase and digits");
  },
});

// =============================================================================
// SECRET IN SERVICE ENV
// =============================================================================

export const secretInServiceEnv = test({
  name: "secret used in service environment",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-env",
  },

  config: `
    import { service, config } from "vyft";

    export const app = service("app", {
      image: "nginx:alpine",
      env: {
        DB_PASSWORD: config("db-password", { secret: true }),
        API_KEY: config("api-key", { secret: true }),
      },
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    await vyft.deploy();

    const dbPassword = await vyft.config.get("db-password");
    const apiKey = await vyft.config.get("api-key");

    assert(dbPassword, "should have db-password");
    assert(apiKey, "should have api-key");
    assert.notStrictEqual(dbPassword, apiKey, "secrets should be unique");
  },
});

// =============================================================================
// SECRET IN CRONJOB ENV
// =============================================================================

export const secretInCronjobEnv = test({
  name: "secret used in cronjob environment",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-cron",
  },

  config: `
    import { cronjob, config } from "vyft";

    export const sync = cronjob("sync", {
      schedule: "0 * * * *",
      image: "alpine:latest",
      command: "echo 'syncing'",
      env: {
        AUTH_TOKEN: config("auth-token", { secret: true }),
      },
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    await vyft.deploy();

    const authToken = await vyft.config.get("auth-token");
    assert(authToken, "should have auth-token");
  },
});

// =============================================================================
// SECRET WITH MANUAL VALUE
// =============================================================================

export const secretManualValue = test({
  name: "manually set secret value",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-manual",
  },

  config: `
    import { service, config } from "vyft";

    export const app = service("app", {
      image: "nginx:alpine",
      env: {
        SECRET: config("manual-secret", { secret: true }),
      },
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    // Set manual value before deploy
    await vyft.config.set("manual-secret", "my-manual-value", { secret: true });

    await vyft.deploy();

    const value = await vyft.config.get("manual-secret");
    assert.strictEqual(value, "my-manual-value", "should use manual value");
  },
});

export const secretManualOverridesGenerated = test({
  name: "manual secret overrides auto-generated",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-override",
  },

  config: `
    import { service, config } from "vyft";

    export const app = service("app", {
      image: "nginx:alpine",
      env: {
        SECRET: config("override-secret", { secret: true }),
      },
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    // Deploy to generate
    await vyft.deploy();
    const generated = await vyft.config.get("override-secret");

    // Override with manual value
    await vyft.config.set("override-secret", "manual-override", { secret: true });
    await vyft.deploy();

    const override = await vyft.config.get("override-secret");
    assert.strictEqual(override, "manual-override");
    assert.notStrictEqual(override, generated);
  },
});

// =============================================================================
// SECRET NON-GENERATED
// =============================================================================

export const secretNonGenerated = test({
  name: "secret with generated=false requires manual value",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-nogen",
  },

  config: `
    import { service, config } from "vyft";

    export const app = service("app", {
      image: "nginx:alpine",
      env: {
        SECRET: config("required-secret", { secret: true, generated: false }),
      },
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    // Deploy without setting should fail
    try {
      await vyft.deploy();
      assert.fail("should fail without required secret");
    } catch {
      // Expected
    }

    // Set and deploy should succeed
    await vyft.config.set("required-secret", "provided-value", { secret: true });
    await vyft.deploy();

    const value = await vyft.config.get("required-secret");
    assert.strictEqual(value, "provided-value");
  },
});

// =============================================================================
// SECRET ISOLATION
// =============================================================================

export const secretIsolatedByStage = test({
  name: "secrets are isolated by stage",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-isolation",
  },

  config: `
    import { config } from "vyft";

    export const apiKey = config("api-key", { secret: true });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);

    // Generate in staging
    await vyft.stage.create("staging");
    await vyft.deploy();
    const stagingKey = await vyft.config.get("api-key");

    // Generate in production
    await vyft.stage.create("production");
    await vyft.deploy();
    const prodKey = await vyft.config.get("api-key");

    // Should be different
    assert.notStrictEqual(stagingKey, prodKey, "secrets should differ by stage");

    // Clean up
    await vyft.stage.use("staging");
    await vyft.destroy();
    await vyft.stage.use("production");
    await vyft.destroy();
  },
});

// =============================================================================
// MULTIPLE SECRETS
// =============================================================================

export const multipleSecretsGenerated = test({
  name: "multiple secrets generated independently",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-multi",
  },

  config: `
    import { service, config } from "vyft";

    export const app = service("app", {
      image: "nginx:alpine",
      env: {
        SECRET1: config("secret-1", { secret: true }),
        SECRET2: config("secret-2", { secret: true }),
        SECRET3: config("secret-3", { secret: true }),
      },
    });
  `,

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    await vyft.deploy();

    const s1 = await vyft.config.get("secret-1");
    const s2 = await vyft.config.get("secret-2");
    const s3 = await vyft.config.get("secret-3");

    assert(s1, "should have secret-1");
    assert(s2, "should have secret-2");
    assert(s3, "should have secret-3");

    // All should be unique
    assert.notStrictEqual(s1, s2);
    assert.notStrictEqual(s2, s3);
    assert.notStrictEqual(s1, s3);
  },
});

// =============================================================================
// SECRET PASSPHRASE
// =============================================================================

export const secretRequiresPassphrase = test({
  name: "secret operations require passphrase",

  config: `
    import { config } from "vyft";

    export const secret = config("test-secret", { secret: true });
  `,

  // Note: No VYFT_PASSPHRASE set
  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    // This test verifies that the CLI prompts for passphrase
    // In automated tests, it may fail or require interaction
    // The exact behavior depends on the CLI implementation
    try {
      await vyft.deploy();
      // If it succeeds without passphrase, that's unexpected for secrets
    } catch {
      // Expected - no passphrase provided
    }
  },
});

// =============================================================================
// SECRET CONFIG LS
// =============================================================================

export const secretConfigLsShowsFlag = test({
  name: "config ls shows secret flag",

  env: {
    VYFT_PASSPHRASE: "test-passphrase-ls",
  },

  run: async ({ id, vyft }) => {
    await vyft.context.create(id);
    await vyft.stage.create(id);

    await vyft.config.set("plain-value", "not-secret");
    await vyft.config.set("secret-value", "is-secret", { secret: true });

    const result = await vyft.config.ls();

    const plain = result.items.find((i) => i.name === "plain-value");
    const secret = result.items.find((i) => i.name === "secret-value");

    assert(plain, "should have plain value");
    assert(secret, "should have secret value");
    assert.strictEqual(plain.secret, false);
    assert.strictEqual(secret.secret, true);
  },
});
