import { ValidationError } from "../../errors.ts";
import type { Secret, SecretConfig } from "../../resource.ts";
import { validateId } from "../../resource.ts";

const DEFAULT_LENGTH = 32;
const MAX_LENGTH = 256;

/**
 * Create a secret. Auto-generated by default; set `generated: false` for user-provided values.
 *
 * @example
 * ```ts
 * secret("db-password")
 * secret("token", { length: 64, alphabet: "0123456789abcdef" })
 * secret("stripe-key", { generated: false })
 * ```
 */
export function secret(id: string, config: SecretConfig = {}): Secret {
  validateId(id);
  if (!("generated" in config) || config.generated !== false) {
    const length = config.length ?? DEFAULT_LENGTH;
    if (length < 1 || length > MAX_LENGTH || !Number.isInteger(length)) {
      throw new ValidationError(
        `Secret "${id}" length must be an integer between 1 and ${MAX_LENGTH}`,
      );
    }
    if (config.alphabet !== undefined && config.alphabet.length < 2) {
      throw new ValidationError(
        `Secret "${id}" alphabet must have at least 2 characters`,
      );
    }
  }
  return { kind: "secret", id, config };
}
