import { mkdir, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createJiti } from "jiti";
import { registry } from "./registry.ts";
import type { ResourceEntry } from "./resource.ts";
import { urn } from "./urn.ts";

// ── Types ────────────────────────────────────────────────────────────

export interface BindingEntry {
  id: string;
  bindings: Array<{ key: string; type: "string" | "number" }>;
}

// ── Config loading ───────────────────────────────────────────────────

const CONFIG_FILES = [
  "vyft.config.ts",
  "vyft.config.js",
  "vyft.config.mjs",
  "vyft.config.mts",
];

async function findConfig(cwd: string): Promise<string | null> {
  for (const name of CONFIG_FILES) {
    const path = resolve(cwd, name);
    try {
      await stat(path);
      return path;
    } catch {
      // Not found
    }
  }
  return null;
}

// ── Collection ───────────────────────────────────────────────────────

function collectEntries(entries: ResourceEntry[]): BindingEntry[] {
  const result: BindingEntry[] = [];
  for (const entry of entries) {
    const parsed = urn.parse(entry.urn);
    if (parsed.resource !== "service") continue;

    result.push({
      id: parsed.id,
      bindings: [
        { key: "host", type: "string" },
        { key: "port", type: "number" },
        { key: "url", type: "string" },
      ],
    });
  }

  return result;
}

function collectEnvKeys(entries: ResourceEntry[]): string[] {
  const keys = new Set<string>(["PORT", "NODE_ENV"]);

  for (const entry of entries) {
    const parsed = urn.parse(entry.urn);
    if (parsed.resource !== "service") continue;

    const env = entry.value["env"];
    if (typeof env === "object" && env !== null) {
      for (const key of Object.keys(env)) {
        keys.add(key);
      }
    }
  }

  return [...keys].sort();
}

// ── Generation ───────────────────────────────────────────────────────

export function generateModuleDts(
  entries: BindingEntry[],
  envKeys: string[],
): string {
  const lines = ["// Auto-generated by vyft — do not edit"];

  const bindingProps: string[] = [];
  for (const entry of entries) {
    const inner = entry.bindings.map(
      (b) => `      readonly ${b.key}: ${b.type};`,
    );
    bindingProps.push(
      `    readonly ${entry.id}: {\n${inner.join("\n")}\n    };`,
    );
  }

  lines.push(`declare module "@vyft/client" {`);
  lines.push(`  export const bindings: {\n${bindingProps.join("\n")}\n  };`);
  lines.push(`  export const env: {`);
  for (const key of envKeys) {
    lines.push(`    readonly ${key}: string;`);
  }
  lines.push(`  };`);
  lines.push(`}`);

  return `${lines.join("\n")}\n`;
}

// ── Public API ───────────────────────────────────────────────────────

export async function generate(cwd: string): Promise<void> {
  const configPath = await findConfig(cwd);
  if (!configPath) return;

  const jiti = createJiti(cwd);

  registry.begin();
  await jiti.import(configPath);
  const entries = registry.collect();

  const bindingEntries = collectEntries(entries);
  const envKeys = collectEnvKeys(entries);

  const outputDir = join(cwd, "node_modules", "@types", "vyft__client");
  await mkdir(outputDir, { recursive: true });
  await writeFile(
    join(outputDir, "package.json"),
    JSON.stringify({ name: "@types/vyft__client", version: "0.0.0" }),
  );
  await writeFile(
    join(outputDir, "index.d.ts"),
    generateModuleDts(bindingEntries, envKeys),
  );
}
