import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Binding, BindValue, Linkable, Service } from "@vyft/primitives";
import { findConfig, loadConfig } from "./config.ts";

// ── Types ────────────────────────────────────────────────────────────

export interface BindingInfo {
  key: string;
  type: "string" | "number";
}

export interface LinkableEntry {
  exportName: string;
  id: string;
  bindings: BindingInfo[];
}

export interface EnvEntry {
  serviceId: string;
  keys: string[];
}

// ── Helpers ──────────────────────────────────────────────────────────

function isBinding(value: unknown): value is Binding {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as Binding).kind === "binding"
  );
}

function isLinkable(value: unknown): value is Linkable {
  if (typeof value !== "object" || value === null) return false;
  const obj = value as Record<string, unknown>;
  const svc = obj["service"];
  return (
    typeof obj["id"] === "string" &&
    typeof svc === "object" &&
    svc !== null &&
    (svc as { kind?: string }).kind === "service"
  );
}

function bindValueType(value: BindValue): "string" | "number" {
  return typeof value === "number" ? "number" : "string";
}

function isService(value: unknown): value is Service {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as Service).kind === "service"
  );
}

// ── Core Functions ───────────────────────────────────────────────────

/** Derive the env var name for generated binding modules. */
export function linkEnvVarName(id: string, key: string): string {
  return `VYFT_BINDING_${id.toUpperCase().replace(/-/g, "_")}_${key.toUpperCase()}`;
}

/** Walk config exports and find objects that satisfy the Linkable interface. */
export function collectLinkables(config: unknown): LinkableEntry[] {
  const entries: LinkableEntry[] = [];
  if (typeof config !== "object" || config === null) return entries;

  for (const [exportName, value] of Object.entries(
    config as Record<string, unknown>,
  )) {
    if (!isLinkable(value)) continue;
    const bindings: BindingInfo[] = [];
    for (const [key, val] of Object.entries(value)) {
      if (isBinding(val)) {
        bindings.push({ key, type: bindValueType(val.value) });
      }
    }
    if (bindings.length > 0) {
      entries.push({ exportName, id: value.id, bindings });
    }
  }

  return entries;
}

/** Walk config exports and collect all services (for type generation). */
export function collectServices(config: unknown): LinkableEntry[] {
  const entries: LinkableEntry[] = [];
  if (typeof config !== "object" || config === null) return entries;

  for (const [exportName, value] of Object.entries(
    config as Record<string, unknown>,
  )) {
    if (isService(value)) {
      entries.push({
        exportName,
        id: value.id,
        bindings: [
          { key: "host", type: "string" },
          { key: "port", type: "number" },
          { key: "url", type: "string" },
        ],
      });
    }
  }

  return entries;
}

/** Compute the set of env var names that come from link bindings. */
function bindingEnvNames(config: unknown): Set<string> {
  const names = new Set<string>();
  if (typeof config !== "object" || config === null) return names;

  for (const value of Object.values(config as Record<string, unknown>)) {
    if (!isLinkable(value)) continue;
    const prefix = `VYFT_BINDING_${value.id.toUpperCase().replace(/-/g, "_")}`;
    for (const [key, val] of Object.entries(value)) {
      if (isBinding(val)) {
        names.add(`${prefix}_${key.toUpperCase()}`);
      }
    }
  }

  return names;
}

/** Walk config exports and collect env keys from services, excluding binding vars. */
export function collectEnvKeys(config: unknown): string[] {
  const keys = new Set<string>(["PORT", "NODE_ENV"]);
  if (typeof config !== "object" || config === null) return [...keys];

  const excluded = bindingEnvNames(config);

  for (const value of Object.values(config as Record<string, unknown>)) {
    if (!isService(value)) continue;
    const env = value.config.env;
    if (env) {
      for (const key of Object.keys(env)) {
        if (!excluded.has(key)) {
          keys.add(key);
        }
      }
    }
  }

  return [...keys].sort();
}

/** Generate TypeScript declarations for bindings and env. */
export function generateEnvDts(
  entries: LinkableEntry[],
  envKeys?: string[],
): string {
  const lines = ["// Auto-generated by vyft generate — do not edit"];

  // bindings — per-service typed accessors keyed by service ID
  const bindingProps: string[] = [];
  for (const entry of entries) {
    const inner = entry.bindings.map((b) => {
      return `    readonly ${b.key}: ${b.type};`;
    });
    bindingProps.push(`  readonly ${entry.id}: {\n${inner.join("\n")}\n  };`);
  }
  lines.push(
    `export declare const bindings: {\n${bindingProps.join("\n")}\n};`,
  );

  // env — typed keys from service env definitions
  const resolvedKeys = envKeys ?? ["PORT", "NODE_ENV"];
  lines.push(`export declare const env: {`);
  for (const key of resolvedKeys) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push(`};`);

  return `${lines.join("\n")}\n`;
}

/** Resolve the @types/vyft__client output directory in the project's node_modules. */
export function resolveClientDir(from: string): string {
  return path.join(from, "node_modules", "@types", "vyft__client");
}

/** Generate a declare module block for @vyft/client. */
export function generateModuleDts(
  entries: LinkableEntry[],
  envKeys?: string[],
): string {
  const lines = ["// Auto-generated by vyft generate — do not edit"];

  // bindings — per-service typed accessors keyed by service ID
  const bindingProps: string[] = [];
  for (const entry of entries) {
    const inner = entry.bindings.map((b) => {
      return `      readonly ${b.key}: ${b.type};`;
    });
    bindingProps.push(
      `    readonly ${entry.id}: {\n${inner.join("\n")}\n    };`,
    );
  }

  const resolvedKeys = envKeys ?? ["PORT", "NODE_ENV"];

  lines.push(`declare module "@vyft/client" {`);
  lines.push(`  export const bindings: {\n${bindingProps.join("\n")}\n  };`);
  lines.push(`  export const env: {`);
  for (const key of resolvedKeys) {
    lines.push(`    readonly ${key}: string;`);
  }
  lines.push(`  };`);
  lines.push(`}`);

  return `${lines.join("\n")}\n`;
}

/** Collect linkables and write types into the output directory. */
export async function writeEnv(
  config: unknown,
  outputDir: string,
): Promise<LinkableEntry[]> {
  // Collect both explicit linkables and services for type generation
  const linkables = collectLinkables(config);
  const services = collectServices(config);
  // Merge entries, preferring linkables (which have explicit bindings)
  const seenIds = new Set(linkables.map((e) => e.id));
  const entries = [...linkables, ...services.filter((e) => !seenIds.has(e.id))];
  const envKeys = collectEnvKeys(config);

  await mkdir(outputDir, { recursive: true });
  await writeFile(
    path.join(outputDir, "package.json"),
    JSON.stringify({ name: "@types/vyft__client", version: "0.0.0" }),
  );
  await writeFile(
    path.join(outputDir, "index.d.ts"),
    generateModuleDts(entries, envKeys),
  );

  return entries;
}

/** Find config, load it, and generate type declarations into .vyft/client. */
export async function generate(cwd: string): Promise<LinkableEntry[]> {
  const configPath = await findConfig(cwd);
  const config = await loadConfig(configPath);
  const clientDir = resolveClientDir(cwd);
  return writeEnv(config, clientDir);
}
