import { ValidationError } from "./errors.ts";
import type { Interpolation, Reference } from "./ref.ts";
import type {
  CronJob,
  CronJobConfig,
  Secret,
  SecretConfig,
  Service,
  ServiceConfig,
  Volume,
  VolumeConfig,
} from "./resource.ts";
import {
  validateCron,
  validateDuration,
  validateId,
  validateRoute,
} from "./resource.ts";

export type BindValue = string | number | Reference | Interpolation;

export interface Binding {
  readonly kind: "binding";
  readonly value: BindValue;
}

export function bindable(value: BindValue): Binding {
  return { kind: "binding", value };
}

const DEFAULT_PORT = 3000;
const DEFAULT_SECRET_LENGTH = 32;
const MAX_SECRET_LENGTH = 256;

/**
 * Create a persistent volume.
 *
 * @example
 * ```ts
 * volume("data")
 * volume("logs", { size: "10Gi" })
 * ```
 */
export function volume(id: string, config: VolumeConfig = {}): Volume {
  validateId(id);
  return { kind: "volume", id, config };
}

/**
 * Create a secret. Auto-generated by default; set `generated: false` for user-provided values.
 *
 * @example
 * ```ts
 * secret("db-password")
 * secret("token", { length: 64, alphabet: "0123456789abcdef" })
 * secret("stripe-key", { generated: false })
 * ```
 */
export function secret(id: string, config: SecretConfig = {}): Secret {
  validateId(id);
  if (!("generated" in config) || config.generated !== false) {
    const length = config.length ?? DEFAULT_SECRET_LENGTH;
    if (length < 1 || length > MAX_SECRET_LENGTH || !Number.isInteger(length)) {
      throw new ValidationError(
        `Secret "${id}" length must be an integer between 1 and ${MAX_SECRET_LENGTH}`,
      );
    }
    if (config.alphabet !== undefined && config.alphabet.length < 2) {
      throw new ValidationError(
        `Secret "${id}" alphabet must have at least 2 characters`,
      );
    }
  }
  return { kind: "secret", id, config };
}

/**
 * Create a long-running service.
 *
 * @example
 * ```ts
 * service("api", { build: "./apps/api", route: "api.example.com" })
 * service("db", { image: "postgres:17", port: 5432 })
 * ```
 */
export function service(id: string, config: ServiceConfig): Service {
  validateId(id);
  if (config.route !== undefined) validateRoute(config.route);
  const port = config.port ?? DEFAULT_PORT;
  if (port < 1 || port > 65535 || !Number.isInteger(port)) {
    throw new ValidationError(
      `Service "${id}" port must be an integer between 1 and 65535`,
    );
  }
  if (config.health) {
    if (config.health.interval !== undefined)
      validateDuration("health.interval", config.health.interval);
    if (config.health.timeout !== undefined)
      validateDuration("health.timeout", config.health.timeout);
    if (config.health.startPeriod !== undefined)
      validateDuration("health.startPeriod", config.health.startPeriod);
  }
  return {
    kind: "service",
    id,
    config,
    host: id,
    port,
    url: `http://${id}:${port}`,
  };
}

/**
 * Create a scheduled job that runs on a cron schedule.
 *
 * @example
 * ```ts
 * cronjob("cleanup", { image: "alpine", schedule: "0 3 * * *", command: "rm -rf /tmp/*" })
 * ```
 */
export function cronjob(id: string, config: CronJobConfig): CronJob {
  validateId(id);
  validateCron(config.schedule);
  if (config.health) {
    if (config.health.interval !== undefined)
      validateDuration("health.interval", config.health.interval);
    if (config.health.timeout !== undefined)
      validateDuration("health.timeout", config.health.timeout);
    if (config.health.startPeriod !== undefined)
      validateDuration("health.startPeriod", config.health.startPeriod);
  }
  return { kind: "cronjob", id, config };
}
