import { ValidationError } from "./errors.ts";
import type { Interpolation, Reference } from "./ref.ts";
import type {
  Config,
  ConfigConfig,
  CronJob,
  CronJobConfig,
  SecretConfig,
  Service,
  ServiceConfig,
  Volume,
  VolumeConfig,
} from "./resource.ts";
import {
  validateCron,
  validateDuration,
  validateId,
  validateRoute,
} from "./resource.ts";

export type BindValue = string | number | Reference | Interpolation;

export interface Binding {
  readonly kind: "binding";
  readonly value: BindValue;
}

export function bindable(value: BindValue): Binding {
  return { kind: "binding", value };
}

const DEFAULT_PORT = 3000;
const DEFAULT_SECRET_LENGTH = 32;
const MAX_SECRET_LENGTH = 256;

/**
 * Create a persistent volume.
 *
 * @example
 * ```ts
 * volume("data")
 * volume("logs", { size: "10Gi" })
 * ```
 */
export function volume(id: string, config: VolumeConfig = {}): Volume {
  validateId(id);
  return { kind: "volume", id, config };
}

export interface ConfigOptions {
  /** Mark this config value as a secret (encrypted at rest). */
  secret?: boolean;
  /** Whether the secret is auto-generated. Only relevant when `secret: true`. @default true */
  generated?: boolean;
  /** Output length for generated secrets. @default 32 */
  length?: number;
  /** Character set for generated secrets. Must have at least 2 characters. */
  alphabet?: string;
}

/**
 * Create a config value. Plain by default; set `secret: true` for encrypted values.
 *
 * @example
 * ```ts
 * config("db-url")
 * config("db-password", { secret: true })
 * config("api-key", { secret: true, generated: false })
 * config("token", { secret: true, length: 64, alphabet: "0123456789abcdef" })
 * ```
 */
export function config(id: string, opts: ConfigOptions = {}): Config {
  validateId(id);
  if (opts.secret) {
    if (opts.generated === false) {
      return { kind: "config", id, config: { generated: false, secret: true } };
    }
    const length = opts.length ?? DEFAULT_SECRET_LENGTH;
    if (length < 1 || length > MAX_SECRET_LENGTH || !Number.isInteger(length)) {
      throw new ValidationError(
        `Config "${id}" length must be an integer between 1 and ${MAX_SECRET_LENGTH}`,
      );
    }
    if (opts.alphabet !== undefined && opts.alphabet.length < 2) {
      throw new ValidationError(
        `Config "${id}" alphabet must have at least 2 characters`,
      );
    }
    const cfg: ConfigConfig =
      opts.alphabet !== undefined
        ? { secret: true, length, alphabet: opts.alphabet }
        : { secret: true, length };
    return { kind: "config", id, config: cfg };
  }
  return { kind: "config", id, config: {} };
}

/**
 * Create a secret. Auto-generated by default; set `generated: false` for user-provided values.
 *
 * @deprecated Use `config(id, { secret: true })` instead.
 *
 * @example
 * ```ts
 * secret("db-password")
 * secret("token", { length: 64, alphabet: "0123456789abcdef" })
 * secret("stripe-key", { generated: false })
 * ```
 */
export function secret(id: string, cfg: SecretConfig = {}): Config {
  validateId(id);
  if (!("generated" in cfg) || cfg.generated !== false) {
    const length = cfg.length ?? DEFAULT_SECRET_LENGTH;
    if (length < 1 || length > MAX_SECRET_LENGTH || !Number.isInteger(length)) {
      throw new ValidationError(
        `Secret "${id}" length must be an integer between 1 and ${MAX_SECRET_LENGTH}`,
      );
    }
    if (cfg.alphabet !== undefined && cfg.alphabet.length < 2) {
      throw new ValidationError(
        `Secret "${id}" alphabet must have at least 2 characters`,
      );
    }
  }
  return { kind: "config", id, config: { ...cfg, secret: true } };
}

/**
 * Create a long-running service.
 *
 * @example
 * ```ts
 * service("api", { build: "./apps/api", route: "api.example.com" })
 * service("db", { image: "postgres:17", port: 5432 })
 * ```
 */
export function service(id: string, config: ServiceConfig): Service {
  validateId(id);
  if (config.route !== undefined) validateRoute(config.route);
  const port = config.port ?? DEFAULT_PORT;
  if (port < 1 || port > 65535 || !Number.isInteger(port)) {
    throw new ValidationError(
      `Service "${id}" port must be an integer between 1 and 65535`,
    );
  }
  if (config.health) {
    if (config.health.interval !== undefined)
      validateDuration("health.interval", config.health.interval);
    if (config.health.timeout !== undefined)
      validateDuration("health.timeout", config.health.timeout);
    if (config.health.startPeriod !== undefined)
      validateDuration("health.startPeriod", config.health.startPeriod);
  }
  return {
    kind: "service",
    id,
    config,
    host: id,
    port,
    url: `http://${id}:${port}`,
  };
}

/**
 * Create a scheduled job that runs on a cron schedule.
 *
 * @example
 * ```ts
 * cronjob("cleanup", { image: "alpine", schedule: "0 3 * * *", command: "rm -rf /tmp/*" })
 * ```
 */
export function cronjob(id: string, config: CronJobConfig): CronJob {
  validateId(id);
  validateCron(config.schedule);
  if (config.health) {
    if (config.health.interval !== undefined)
      validateDuration("health.interval", config.health.interval);
    if (config.health.timeout !== undefined)
      validateDuration("health.timeout", config.health.timeout);
    if (config.health.startPeriod !== undefined)
      validateDuration("health.startPeriod", config.health.startPeriod);
  }
  return { kind: "cronjob", id, config };
}
