import { ValidationError } from "./errors.ts";
import type { EnvValue, Interpolation, Reference } from "./ref.ts";
import type {
  BindMount,
  Config,
  ConfigConfig,
  CronJob,
  CronJobConfig,
  Linkable,
  SecretConfig,
  Service,
  ServiceConfig,
  Volume,
  VolumeConfig,
} from "./resource.ts";
import {
  MOUNTABLE,
  validateCron,
  validateDuration,
  validateId,
  validateRoute,
} from "./resource.ts";

export type BindValue = string | number | Reference | Interpolation;

export interface Binding {
  readonly kind: "binding";
  readonly value: BindValue;
}

export function bindable(value: BindValue): Binding {
  return { kind: "binding", value };
}

const DEFAULT_PORT = 3000;
const DEFAULT_SECRET_LENGTH = 32;
const MAX_SECRET_LENGTH = 256;

/**
 * Create a persistent volume.
 *
 * @example
 * ```ts
 * volume("data")
 * volume("logs", { size: "10Gi" })
 * ```
 */
export function volume(id: string, config: VolumeConfig = {}): Volume {
  validateId(id);
  return { kind: "volume", id, config, [MOUNTABLE]: true };
}

export function bind(id: string, hostPath: string): BindMount {
  validateId(id);
  return { kind: "bind", id, hostPath, [MOUNTABLE]: true };
}

export interface ConfigOptions {
  /** Mark this config value as a secret (encrypted at rest). */
  secret?: boolean;
  /** Whether the secret is auto-generated. Only relevant when `secret: true`. @default true */
  generated?: boolean;
  /** Output length for generated secrets. @default 32 */
  length?: number;
  /** Character set for generated secrets. Must have at least 2 characters. */
  alphabet?: string;
}

/**
 * Create a config value. Plain by default; set `secret: true` for encrypted values.
 *
 * @example
 * ```ts
 * config("db-url")
 * config("db-password", { secret: true })
 * config("api-key", { secret: true, generated: false })
 * config("token", { secret: true, length: 64, alphabet: "0123456789abcdef" })
 * ```
 */
export function config(id: string, opts: ConfigOptions = {}): Config {
  validateId(id);
  if (opts.secret) {
    if (opts.generated === false) {
      return { kind: "config", id, config: { generated: false, secret: true } };
    }
    const length = opts.length ?? DEFAULT_SECRET_LENGTH;
    if (length < 1 || length > MAX_SECRET_LENGTH || !Number.isInteger(length)) {
      throw new ValidationError(
        `Config "${id}" length must be an integer between 1 and ${MAX_SECRET_LENGTH}`,
      );
    }
    if (opts.alphabet !== undefined && opts.alphabet.length < 2) {
      throw new ValidationError(
        `Config "${id}" alphabet must have at least 2 characters`,
      );
    }
    const cfg: ConfigConfig =
      opts.alphabet !== undefined
        ? { secret: true, length, alphabet: opts.alphabet }
        : { secret: true, length };
    return { kind: "config", id, config: cfg };
  }
  return { kind: "config", id, config: {} };
}

/**
 * Create a secret. Auto-generated by default; set `generated: false` for user-provided values.
 *
 * @deprecated Use `config(id, { secret: true })` instead.
 *
 * @example
 * ```ts
 * secret("db-password")
 * secret("token", { length: 64, alphabet: "0123456789abcdef" })
 * secret("stripe-key", { generated: false })
 * ```
 */
export function secret(id: string, cfg: SecretConfig = {}): Config {
  validateId(id);
  if (!("generated" in cfg) || cfg.generated !== false) {
    const length = cfg.length ?? DEFAULT_SECRET_LENGTH;
    if (length < 1 || length > MAX_SECRET_LENGTH || !Number.isInteger(length)) {
      throw new ValidationError(
        `Secret "${id}" length must be an integer between 1 and ${MAX_SECRET_LENGTH}`,
      );
    }
    if (cfg.alphabet !== undefined && cfg.alphabet.length < 2) {
      throw new ValidationError(
        `Secret "${id}" alphabet must have at least 2 characters`,
      );
    }
  }
  return { kind: "config", id, config: { ...cfg, secret: true } };
}

/**
 * Create a long-running service.
 *
 * @example
 * ```ts
 * service("api", { build: "./apps/api", route: "api.example.com" })
 * service("db", { image: "postgres:17", port: 5432 })
 * ```
 */
function isBinding(value: unknown): value is Binding {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as Binding).kind === "binding"
  );
}

function bindingToEnvValue(value: BindValue): EnvValue {
  if (typeof value === "number") return String(value);
  return value; // string | Reference | Interpolation are already EnvValue
}

function expandLink(linkItems: Linkable[]): {
  env: Record<string, EnvValue>;
  deps: Service[];
} {
  const env: Record<string, EnvValue> = {};
  const deps: Service[] = [];
  for (const item of linkItems) {
    deps.push(item.service);
    const prefix = item.id.toUpperCase().replace(/-/g, "_");
    for (const [key, value] of Object.entries(item)) {
      if (isBinding(value)) {
        const envName = `${prefix}_${key.toUpperCase()}`;
        env[envName] = bindingToEnvValue(value.value);
      }
    }
  }
  return { env, deps };
}

export function service(id: string, config: ServiceConfig): Service {
  validateId(id);

  // Expand link items into env vars and dependsOn, then strip link from config
  const { link: linkItems, ...restConfig } = config;
  let finalConfig: ServiceConfig = restConfig;
  if (linkItems) {
    const { env, deps } = expandLink(linkItems);
    finalConfig = {
      ...restConfig,
      env: { ...env, ...restConfig.env },
      dependsOn: [...deps, ...(restConfig.dependsOn ?? [])],
    };
  }

  if (finalConfig.route !== undefined) validateRoute(finalConfig.route);
  const port = finalConfig.port ?? DEFAULT_PORT;
  if (port < 1 || port > 65535 || !Number.isInteger(port)) {
    throw new ValidationError(
      `Service "${id}" port must be an integer between 1 and 65535`,
    );
  }
  if (finalConfig.health) {
    if (finalConfig.health.interval !== undefined)
      validateDuration("health.interval", finalConfig.health.interval);
    if (finalConfig.health.timeout !== undefined)
      validateDuration("health.timeout", finalConfig.health.timeout);
    if (finalConfig.health.startPeriod !== undefined)
      validateDuration("health.startPeriod", finalConfig.health.startPeriod);
  }
  return {
    kind: "service",
    id,
    config: finalConfig,
    host: id,
    port,
    url: `http://${id}:${port}`,
  };
}

/**
 * Create a scheduled job that runs on a cron schedule.
 *
 * @example
 * ```ts
 * cronjob("cleanup", { image: "alpine", schedule: "0 3 * * *", command: "rm -rf /tmp/*" })
 * ```
 */
export function cronjob(id: string, config: CronJobConfig): CronJob {
  validateId(id);

  // Expand link items into env vars, then strip link from config
  const { link: linkItems, ...restConfig } = config;
  let finalConfig: CronJobConfig = restConfig;
  if (linkItems) {
    const { env } = expandLink(linkItems);
    finalConfig = {
      ...restConfig,
      env: { ...env, ...restConfig.env },
    };
  }

  validateCron(finalConfig.schedule);
  if (finalConfig.health) {
    if (finalConfig.health.interval !== undefined)
      validateDuration("health.interval", finalConfig.health.interval);
    if (finalConfig.health.timeout !== undefined)
      validateDuration("health.timeout", finalConfig.health.timeout);
    if (finalConfig.health.startPeriod !== undefined)
      validateDuration("health.startPeriod", finalConfig.health.startPeriod);
  }
  return { kind: "cronjob", id, config: finalConfig };
}

export interface SiteOptions {
  /** Path to directory with package.json containing a "build" script. */
  path: string;
  /** Public domain, e.g. "example.com". */
  domain?: string;
  /** Custom build command. @default "npm run build" */
  buildCommand?: string;
  /** Output directory relative to path. @default "dist" */
  outDir?: string;
  /** SPA fallback to index.html. @default true */
  spa?: boolean;
}

export interface Site extends Linkable {
  readonly service: Service;
  readonly url: Binding;
  readonly host: Binding;
  readonly port: Binding;
  readonly path: string;
  readonly buildCommand: string;
  readonly outDir: string;
  readonly spa: boolean;
}

/**
 * Create a static site served by nginx.
 *
 * @example
 * ```ts
 * site("web", { path: "./apps/web", domain: "example.com" })
 * ```
 */
export function site(id: string, opts: SiteOptions): Site {
  const buildCommand = opts.buildCommand ?? "npm run build";
  const outDir = opts.outDir ?? "dist";
  const spa = opts.spa ?? true;

  const svc = service(id, {
    image: "nginx:alpine",
    port: 80,
    ...(opts.domain ? { route: opts.domain } : {}),
    health: {
      command: "curl -f http://localhost/ || exit 1",
      interval: "5s",
      retries: 3,
    },
  });

  return {
    id,
    service: svc,
    url: bindable(`http://${id}:80`),
    host: bindable(id),
    port: bindable(80),
    path: opts.path,
    buildCommand,
    outDir,
    spa,
  };
}
