apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: kube-system
spec:
  chart: loki-stack
  repo: https://grafana.github.io/helm-charts
  version: 2.10.2
  targetNamespace: observability
  createNamespace: true
  valuesContent: |-
    loki:
      enabled: true
      persistence:
        enabled: false
    promtail:
      enabled: true
    grafana:
      enabled: false
    prometheus:
      enabled: false
