import type { ChildProcess } from "node:child_process";
import { spawn } from "node:child_process";
import { watch } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type {
  BindValue,
  EnvValue,
  RuntimeName,
  Secret,
  Service,
} from "@vyft/core";
import {
  findConfig,
  generateSecret,
  loadConfig,
  projectInfo,
  resolve,
} from "@vyft/core";
import * as log from "@vyft/core/logger";
import type { BindingTree } from "@vyft/engine";
import {
  buildGraph,
  collect,
  collectBindings,
  deploy as engineDeploy,
} from "@vyft/engine";
import {
  createFileStore,
  decrypt,
  encrypt,
  resolvePassphrase,
} from "@vyft/store";
import type { Command } from "commander";
import { createRuntime } from "../../runtime-factory.ts";
import { withLifecycle } from "../lifecycle.ts";

// ── Helpers ──────────────────────────────────────────────────────────

/** Convert a camelCase string to UPPER_SNAKE_CASE. */
function toUpperSnake(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

/** Build env var name from a dot-separated binding path. */
function envVarName(segments: string[]): string {
  return `VYFT_${segments.map(toUpperSnake).join("_")}`;
}

// ── Service Classification ───────────────────────────────────────────

interface ClassifiedServices {
  infra: Service[];
  dev: Service[];
  buildOnly: Service[];
}

function classifyServices(
  resources: import("@vyft/core").Resource[],
): ClassifiedServices {
  const infra: Service[] = [];
  const dev: Service[] = [];
  const buildOnly: Service[] = [];

  for (const r of resources) {
    if (r.kind !== "service") continue;
    if (r.config.dev) {
      dev.push(r);
    } else if (r.config.image && !r.config.build) {
      infra.push(r);
    } else if (r.config.build) {
      buildOnly.push(r);
      log.info('skipping build-only service "%s" (no dev field)', r.id);
    }
  }

  return { infra, dev, buildOnly };
}

// ── Binding Resolution ───────────────────────────────────────────────

interface ResolvedBinding {
  envVar: string;
  value: string;
  originalType: "string" | "number";
}

function resolveBindValue(
  value: BindValue,
  secrets: ReadonlyMap<string, string>,
  infraIds: Set<string>,
): { resolved: string; type: "string" | "number" } {
  if (typeof value === "number") {
    return { resolved: String(value), type: "number" };
  }
  if (typeof value === "string") {
    // If the string equals an infra service id, replace with localhost
    const resolved = infraIds.has(value) ? "localhost" : value;
    return { resolved, type: "string" };
  }
  // Reference or Interpolation — resolve then replace hostnames
  let resolved = resolve(value as EnvValue, secrets);
  for (const id of infraIds) {
    resolved = resolved.replaceAll(id, "localhost");
  }
  return { resolved, type: "string" };
}

function flattenBindings(
  tree: Record<string, BindingTree>,
  secrets: ReadonlyMap<string, string>,
  infraIds: Set<string>,
  prefix: string[] = [],
): ResolvedBinding[] {
  const result: ResolvedBinding[] = [];
  for (const [key, node] of Object.entries(tree)) {
    const segments = [...prefix, key];
    if (node.kind === "leaf") {
      const { resolved, type } = resolveBindValue(
        node.value,
        secrets,
        infraIds,
      );
      result.push({
        envVar: envVarName(segments),
        value: resolved,
        originalType: type,
      });
    } else {
      result.push(
        ...flattenBindings(node.children, secrets, infraIds, segments),
      );
    }
  }
  return result;
}

// ── Code Generation ──────────────────────────────────────────────────

function generateResourceJs(
  tree: Record<string, BindingTree>,
  secrets: ReadonlyMap<string, string>,
  infraIds: Set<string>,
): string {
  const lines = ["// Auto-generated by vyft dev"];

  function emitValue(node: BindingTree, segments: string[]): string {
    if (node.kind === "leaf") {
      const envVar = envVarName(segments);
      const { type } = resolveBindValue(node.value, secrets, infraIds);
      return type === "number"
        ? `Number(process.env.${envVar})`
        : `process.env.${envVar}`;
    }
    const entries = Object.entries(node.children).map(([k, child]) => {
      const val = emitValue(child, [...segments, k]);
      return `  ${k}: ${val},`;
    });
    return `{\n${entries.join("\n")}\n}`;
  }

  for (const [key, node] of Object.entries(tree)) {
    const val = emitValue(node, [key]);
    lines.push(`export const ${key} = ${val};`);
  }

  return `${lines.join("\n")}\n`;
}

function generateResourceDts(
  tree: Record<string, BindingTree>,
  secrets: ReadonlyMap<string, string>,
  infraIds: Set<string>,
): string {
  const lines = ["// Auto-generated by vyft dev"];

  function emitType(
    node: BindingTree,
    segments: string[],
    indent: string,
  ): string {
    if (node.kind === "leaf") {
      const { type } = resolveBindValue(node.value, secrets, infraIds);
      return type === "number" ? "number" : "string";
    }
    const entries = Object.entries(node.children).map(([k, child]) => {
      const t = emitType(child, [...segments, k], `${indent}  `);
      return `${indent}  readonly ${k}: ${t};`;
    });
    return `{\n${entries.join("\n")}\n${indent}}`;
  }

  for (const [key, node] of Object.entries(tree)) {
    const t = emitType(node, [key], "");
    lines.push(`export declare const ${key}: ${t};`);
  }

  return `${lines.join("\n")}\n`;
}

// ── Console prefix colors ────────────────────────────────────────────

const COLORS = [
  "\x1b[32m", // green
  "\x1b[33m", // yellow
  "\x1b[34m", // blue
  "\x1b[35m", // magenta
  "\x1b[36m", // cyan
];
const RESET = "\x1b[0m";

// ── Dev Command ──────────────────────────────────────────────────────

interface DevState {
  context: string;
  project: string;
  runtimeName: RuntimeName;
  unlock: () => Promise<void>;
  ac: AbortController;
}

export function registerDev(program: Command): void {
  program
    .command("dev")
    .description("Start local development environment")
    .option("-c, --config <path>", "Path to config file", "vyft.config.ts")
    .action(
      withLifecycle<DevState>({
        async setup() {
          const { root, context, project, runtimeName } = await projectInfo();
          const store = createFileStore(root);
          const unlock = await store.lock(context, project);
          const ac = new AbortController();

          // Signal handling
          const onSignal = () => ac.abort();
          process.on("SIGINT", onSignal);
          process.on("SIGTERM", onSignal);

          return { context, project, runtimeName, unlock, ac };
        },

        async run({ context, project, runtimeName, ac }) {
          const configPath = await findConfig(process.cwd());
          const devProcesses = new Map<string, ChildProcess>();

          async function loadAndRun(): Promise<void> {
            const config = await loadConfig(configPath);
            log.info("loaded config from %s", configPath);

            const resources = collect(config);
            const { infra, dev } = classifyServices(resources);
            const infraIds = new Set(infra.map((s) => s.id));

            // Resolve secrets
            const { root } = await projectInfo();
            const store = createFileStore(root);
            const previous = await store.load(context, project);
            const passphrase = await resolvePassphrase();
            const secretMap = new Map<string, string>();
            if (previous?.secrets) {
              const raw = JSON.parse(
                decrypt(previous.secrets, passphrase),
              ) as Record<string, string>;
              for (const [k, v] of Object.entries(raw)) secretMap.set(k, v);
            }

            // Auto-generate missing secrets
            const secretResources = resources.filter(
              (r): r is Secret => r.kind === "secret",
            );
            let secretsChanged = false;
            for (const sr of secretResources) {
              if (!secretMap.has(sr.id)) {
                if (sr.config.generated === false) continue;
                secretMap.set(
                  sr.id,
                  generateSecret(sr.config.length, sr.config.alphabet),
                );
                secretsChanged = true;
              }
            }

            if (secretsChanged) {
              const allSecrets = Object.fromEntries(secretMap);
              const encrypted = encrypt(JSON.stringify(allSecrets), passphrase);
              await store.save(context, project, {
                version: previous?.version ?? 1,
                manifest: { timestamp: new Date().toISOString(), tool: "vyft" },
                resources: previous?.resources ?? [],
                secrets: encrypted,
              });
            }

            // Collect bindings
            const bindings = collectBindings(config);
            const resolved = flattenBindings(bindings, secretMap, infraIds);

            // Generate resource bindings files
            const thisFile = fileURLToPath(import.meta.url);
            const distDir = path.resolve(path.dirname(thisFile), "..", "..");
            const fs = await import("node:fs/promises");
            await fs.writeFile(
              path.join(distDir, "resource.js"),
              generateResourceJs(bindings, secretMap, infraIds),
            );
            await fs.writeFile(
              path.join(distDir, "resource.d.ts"),
              generateResourceDts(bindings, secretMap, infraIds),
            );
            log.info("generated resource bindings (%d vars)", resolved.length);

            // Build binding env vars
            const bindingEnv: Record<string, string> = {};
            for (const b of resolved) {
              bindingEnv[b.envVar] = b.value;
            }

            // Deploy infra services
            if (infra.length > 0) {
              log.info("deploying %d infra service(s)...", infra.length);

              // Build port bindings: expose each infra service's port on the same host port
              const portBindingsMap: Record<string, number> = {};
              for (const svc of infra) {
                portBindingsMap[svc.id] = svc.port;
              }

              // Filter resources to infra services + their deps (volumes, secrets)
              const graph = buildGraph(resources);
              const infraDepIds = new Set<string>();
              for (const svc of infra) {
                infraDepIds.add(svc.id);
                const deps = graph.dependencies.get(svc.id);
                if (deps) {
                  for (const dep of deps) infraDepIds.add(dep);
                }
              }
              const infraResources = resources.filter((r) =>
                infraDepIds.has(r.id),
              );

              const runtimeOpts = {
                project,
                secrets: secretMap,
                portBindings: portBindingsMap,
              };
              const runtime = createRuntime(runtimeName, runtimeOpts);

              await engineDeploy(infraResources, [], runtime);
              log.info("infra services deployed");
            }

            // Kill existing dev processes
            for (const [id, proc] of devProcesses) {
              log.info('stopping dev process "%s"', id);
              proc.kill("SIGTERM");
            }
            devProcesses.clear();

            // Spawn dev processes
            let colorIdx = 0;
            for (const svc of dev) {
              const devConfig = svc.config.dev;
              if (!devConfig) continue;

              const color = COLORS[colorIdx++ % COLORS.length];
              const prefix = `${color}[${svc.id}]${RESET}`;
              const svcId = svc.id;

              // Resolve service env vars, replacing infra hostnames with localhost
              const svcEnv: Record<string, string> = {};
              if (svc.config.env) {
                for (const [key, val] of Object.entries(svc.config.env)) {
                  let resolved = resolve(val, secretMap);
                  for (const id of infraIds) {
                    resolved = resolved.replaceAll(id, "localhost");
                  }
                  svcEnv[key] = resolved;
                }
              }

              const child = spawn("sh", ["-c", devConfig.command], {
                cwd: devConfig.cwd ?? process.cwd(),
                env: { ...process.env, ...svcEnv, ...bindingEnv },
                stdio: ["ignore", "pipe", "pipe"],
              });

              child.stdout?.on("data", (data: Buffer) => {
                for (const line of data.toString().split("\n")) {
                  if (line) process.stdout.write(`${prefix} ${line}\n`);
                }
              });

              child.stderr?.on("data", (data: Buffer) => {
                for (const line of data.toString().split("\n")) {
                  if (line) process.stderr.write(`${prefix} ${line}\n`);
                }
              });

              child.on("exit", (code, signal) => {
                if (!ac.signal.aborted) {
                  log.warn(
                    'dev process "%s" exited (code=%s, signal=%s)',
                    svcId,
                    code,
                    signal,
                  );
                }
                devProcesses.delete(svcId);
              });

              devProcesses.set(svcId, child);
              log.info(
                'started dev process "%s": %s',
                svcId,
                devConfig.command,
              );
            }
          }

          // Initial load
          await loadAndRun();

          // Config file watching
          let debounceTimer: ReturnType<typeof setTimeout> | null = null;
          const watcher = watch(configPath, { signal: ac.signal }, () => {
            if (debounceTimer) clearTimeout(debounceTimer);
            debounceTimer = setTimeout(async () => {
              log.info("config changed, reloading...");
              try {
                await loadAndRun();
              } catch (err) {
                log.error(
                  "reload failed: %s",
                  err instanceof Error ? err.message : err,
                );
              }
            }, 300);
          });

          watcher.on("error", (err) => {
            if (
              (err as NodeJS.ErrnoException).code !== "ERR_USE_AFTER_CLOSE" &&
              (err as NodeJS.ErrnoException).code !== "ABORT_ERR"
            ) {
              log.error("watcher error: %s", err.message);
            }
          });

          // Block until abort
          await new Promise<void>((resolve) => {
            if (ac.signal.aborted) return resolve();
            ac.signal.addEventListener("abort", () => resolve(), {
              once: true,
            });
          });

          // Cleanup dev processes
          for (const [id, proc] of devProcesses) {
            log.info('stopping dev process "%s"', id);
            proc.kill("SIGTERM");
          }

          // Grace period
          if (devProcesses.size > 0) {
            await new Promise((r) => setTimeout(r, 500));
            for (const [, proc] of devProcesses) {
              proc.kill("SIGKILL");
            }
          }
          devProcesses.clear();
        },

        async cleanup(state) {
          if (state) {
            state.ac.abort();
            await state.unlock();
          }
        },
      }),
    );
}
